import pandas as pd
import numpy as np
import pickle
import os

case_ind = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

with open('multiplication_index', 'rb') as fp:
    multiplication_index_data = pickle.load(fp)

if isinstance(multiplication_index_data, list):
    print("Detected List format! Converting to Dictionary...")
    multiplication_index = {}
    for idx, node_list in enumerate(multiplication_index_data):
        multiplication_index[idx + 1] = node_list
else:
    multiplication_index = multiplication_index_data

## ======================================================
# Convert solutions generated by RL to json files
## ======================================================
with open('RLMD/ac_mu_5_rs_100_solution', 'rb') as fp:
    rl = pickle.load(fp)

c_dict_solution = rl[1]

cases_index_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

dsp_low = 0
dsp_up = 200

for graph_index in cases_index_list:
    
    if graph_index not in multiplication_index:
        continue

    current_mul = multiplication_index[graph_index]
    solution_len = len(current_mul)

    mapping_filename = 'info_case_' + str(case_ind[graph_index]) + '_node_number_mapping'
    
    inv_map = None
    if os.path.exists(mapping_filename):
        with open(mapping_filename, 'rb') as fp:
            mapping = pickle.load(fp)
        inv_map = {v: k for k, v in mapping.items()}
        print(f"Case {case_ind[graph_index]}: Real DFG Mode (Mapping loaded)")
    else:
        print(f"Case {case_ind[graph_index]}: Synthetic DFG Mode")

    solution = []
    target = []

    for dsp_target in range(dsp_low, dsp_up):
        if (graph_index, dsp_target) in c_dict_solution:
            current_solution_set = c_dict_solution[graph_index, dsp_target]
            
            for j in range(len(current_solution_set)): # j th solution
                current_solution = []
                if len(current_solution_set[j]) == solution_len:
                    temp_sol_set = current_solution_set[j]
                else:
                    temp_sol_set = current_solution_set[j] + [1 for i in range(int(solution_len - len(current_solution_set[j])))]
                
                for k in range(solution_len):
                    if temp_sol_set[k] == 1:
                        target_node_idx = current_mul[k]

                        if inv_map is not None:
                            try:
                                val = inv_map[target_node_idx] + 1
                            except KeyError:
                                val = target_node_idx + 1
                        else:
                            val = target_node_idx + 1
                            
                        current_solution.append(val)
                
                solution.append(current_solution)
            
            target.extend([dsp_target for _ in range(len(current_solution_set))])

    if len(solution) > 0:
        df = pd.DataFrame([target, solution], index=["target_DSP", "solution"])
        
        if not os.path.exists('RL_solution/mu_2'):
            os.makedirs('RL_solution/mu_2')
            
        save_path = r'RL_solution/mu_2/case_' + str(case_ind[graph_index]) + '_RL_solution_mu_2.json'
        df.to_json(save_path)
        print(f"Saved: {save_path}")
    else:
        print(f"No solution found for graph_index {graph_index}")
