

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "5", "8", "10", "12", "22", "24", "27", "33", "36", "39", "42", "45", "46"],
		"CDFG" : "case_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "3157", "EstimateLatencyMax" : "3157",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "in_data_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332", "Port" : "in_data_0", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "10", "SubInstance" : "grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376", "Port" : "in_data_0", "Inst_start_state" : "9", "Inst_end_state" : "10"},
					{"ID" : "12", "SubInstance" : "grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385", "Port" : "in_data_0", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "42", "SubInstance" : "grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463", "Port" : "in_data_0", "Inst_start_state" : "25", "Inst_end_state" : "26"}]},
			{"Name" : "in_data_1", "Type" : "Memory", "Direction" : "X"},
			{"Name" : "in_data_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332", "Port" : "in_data_2", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "12", "SubInstance" : "grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385", "Port" : "in_data_2", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "22", "SubInstance" : "grp_case_3_Pipeline_L_s1_1_fu_394", "Port" : "in_data_2", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "27", "SubInstance" : "grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412", "Port" : "in_data_2", "Inst_start_state" : "17", "Inst_end_state" : "18"},
					{"ID" : "33", "SubInstance" : "grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435", "Port" : "in_data_2", "Inst_start_state" : "19", "Inst_end_state" : "20"}]},
			{"Name" : "in_data_3", "Type" : "Memory", "Direction" : "X"},
			{"Name" : "in_data_4", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332", "Port" : "in_data_4", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "27", "SubInstance" : "grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412", "Port" : "in_data_4", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "in_data_5", "Type" : "Memory", "Direction" : "X"},
			{"Name" : "in_data_6", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332", "Port" : "in_data_6", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "27", "SubInstance" : "grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412", "Port" : "in_data_6", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "in_data_7", "Type" : "Memory", "Direction" : "X"},
			{"Name" : "in_data_8", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321", "Port" : "in_data_8", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "5", "SubInstance" : "grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332", "Port" : "in_data_8", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "24", "SubInstance" : "grp_case_3_Pipeline_L_s2_1_fu_403", "Port" : "in_data_8", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "39", "SubInstance" : "grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453", "Port" : "in_data_8", "Inst_start_state" : "23", "Inst_end_state" : "24"}]},
			{"Name" : "in_data_9", "Type" : "Memory", "Direction" : "X"},
			{"Name" : "in_data_10", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332", "Port" : "in_data_10", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "in_data_11", "Type" : "Memory", "Direction" : "X"},
			{"Name" : "in_data_12", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "8", "SubInstance" : "grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363", "Port" : "in_data_12", "Inst_start_state" : "7", "Inst_end_state" : "8"},
					{"ID" : "42", "SubInstance" : "grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463", "Port" : "in_data_12", "Inst_start_state" : "25", "Inst_end_state" : "26"}]},
			{"Name" : "in_data_13", "Type" : "Memory", "Direction" : "X"},
			{"Name" : "in_data_14", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332", "Port" : "in_data_14", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "27", "SubInstance" : "grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412", "Port" : "in_data_14", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "in_data_15", "Type" : "Memory", "Direction" : "X"},
			{"Name" : "in_scalar", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "out_data_0", "Type" : "None", "Direction" : "O"},
			{"Name" : "out_data_1", "Type" : "None", "Direction" : "O"},
			{"Name" : "out_data_2", "Type" : "None", "Direction" : "O"},
			{"Name" : "out_data_3", "Type" : "None", "Direction" : "O"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.m64_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321", "Parent" : "0", "Child" : ["3", "4"],
		"CDFG" : "case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "shl_ln94_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_data_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "sext_ln100", "Type" : "None", "Direction" : "I"},
			{"Name" : "m27_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "phi_ln103_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "L_n2_1_L_n2_2_L_n2_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321.mul_8s_4s_12_1_1_U1", "Parent" : "2"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321.flow_control_loop_pipe_sequential_init_U", "Parent" : "2"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332", "Parent" : "0", "Child" : ["6", "7"],
		"CDFG" : "case_3_Pipeline_L_n3_1_L_n3_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "68", "EstimateLatencyMax" : "68",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "m27_1_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_data_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "in_data_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "in_data_10", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "in_data_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "in_data_14", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "in_scalar_load_2_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_data_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "in_data_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "m43_cast70", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_i4971_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln108_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "m27_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "add_i5025_phi_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "add_i4863_phi_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "phi_ln127_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i4798204_phi_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "add_i4277_phi_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i12_i4097189_phi_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "L_n3_1_L_n3_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332.mul_5s_5s_5_1_1_U8", "Parent" : "5"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332.flow_control_loop_pipe_sequential_init_U", "Parent" : "5"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363", "Parent" : "0", "Child" : ["9"],
		"CDFG" : "case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "m27_2_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_data_12", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "conv_i3873_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln131", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln22", "Type" : "None", "Direction" : "I"},
			{"Name" : "m27_3_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "m124_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "L_n4_1_L_n4_2_L_n4_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363.flow_control_loop_pipe_sequential_init_U", "Parent" : "8"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376", "Parent" : "0", "Child" : ["11"],
		"CDFG" : "case_3_Pipeline_L_n5_1_L_n5_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "66", "EstimateLatencyMax" : "66",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "m27_3_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_data_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "m27_4_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "phi_ln146_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "L_n5_1_L_n5_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376.flow_control_loop_pipe_sequential_init_U", "Parent" : "10"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385", "Parent" : "0", "Child" : ["13", "14", "15", "16", "17", "18", "19", "20", "21"],
		"CDFG" : "case_3_Pipeline_L_m1_1_L_m1_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "260", "EstimateLatencyMax" : "260",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "in_data_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "m64", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "in_data_2", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "L_m1_1_L_m1_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage2", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage2_subdone", "QuitState" : "ap_ST_fsm_pp0_stage2", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage2_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385.mul_8s_8s_11_1_1_U40", "Parent" : "12"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385.mul_8s_8s_11_1_1_U41", "Parent" : "12"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385.mul_8s_8s_11_1_1_U42", "Parent" : "12"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385.mul_8s_8s_11_1_1_U43", "Parent" : "12"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385.mul_8s_8s_11_1_1_U44", "Parent" : "12"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385.mul_8s_8s_11_1_1_U45", "Parent" : "12"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385.mul_8s_8s_11_1_1_U46", "Parent" : "12"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385.mul_8s_8s_11_1_1_U47", "Parent" : "12"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385.flow_control_loop_pipe_sequential_init_U", "Parent" : "12"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_s1_1_fu_394", "Parent" : "0", "Child" : ["23"],
		"CDFG" : "case_3_Pipeline_L_s1_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "m27_4_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_data_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "sext_ln22_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "m27_7_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "L_s1_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_s1_1_fu_394.flow_control_loop_pipe_sequential_init_U", "Parent" : "22"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_s2_1_fu_403", "Parent" : "0", "Child" : ["25", "26"],
		"CDFG" : "case_3_Pipeline_L_s2_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "11", "EstimateLatencyMax" : "11",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "m27_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_data_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "sext_ln184", "Type" : "None", "Direction" : "I"},
			{"Name" : "m27_10_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "L_s2_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_s2_1_fu_403.mul_7s_4s_7_1_1_U56", "Parent" : "24"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_s2_1_fu_403.flow_control_loop_pipe_sequential_init_U", "Parent" : "24"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412", "Parent" : "0", "Child" : ["28", "29", "30", "31", "32"],
		"CDFG" : "case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "519", "EstimateLatencyMax" : "519",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "m27_10_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_data_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "in_data_14", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "in_data_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "in_data_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "in_scalar_load_2_cast31", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln205", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln22_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i4798204_phi_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i12_i180886", "Type" : "None", "Direction" : "I"},
			{"Name" : "m93_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "m27_13_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mul_i2259_phi_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_phi22_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "L_n8_1_L_n8_2_L_n8_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter6", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter6", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412.mul_7s_4s_11_1_1_U62", "Parent" : "27"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412.mul_5s_5s_5_1_1_U63", "Parent" : "27"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412.mul_9s_8s_13_1_1_U64", "Parent" : "27"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412.mac_muladd_6s_4s_13s_14_4_1_U65", "Parent" : "27"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412.flow_control_loop_pipe_sequential_init_U", "Parent" : "27"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435", "Parent" : "0", "Child" : ["34", "35"],
		"CDFG" : "case_3_Pipeline_L_n9_1_L_n9_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "67", "EstimateLatencyMax" : "67",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "m27_13_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_data_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "sext_ln220", "Type" : "None", "Direction" : "I"},
			{"Name" : "m27_15_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "L_n9_1_L_n9_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435.mul_8s_4s_10_1_1_U84", "Parent" : "33"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435.flow_control_loop_pipe_sequential_init_U", "Parent" : "33"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444", "Parent" : "0", "Child" : ["37", "38"],
		"CDFG" : "case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "516", "EstimateLatencyMax" : "516",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "m27_15_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "m64", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "sext_ln228", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i12_i132751", "Type" : "None", "Direction" : "I"},
			{"Name" : "m27_17_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "L_n10_1_L_n10_2_L_n10_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444.mul_15s_8s_15_1_1_U90", "Parent" : "36"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444.flow_control_loop_pipe_sequential_init_U", "Parent" : "36"},
	{"ID" : "39", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453", "Parent" : "0", "Child" : ["40", "41"],
		"CDFG" : "case_3_Pipeline_L_n11_1_L_n11_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "69", "EstimateLatencyMax" : "69",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "m27_17_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_data_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "in_scalar_load_6_cast34", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln22_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "m27_19_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "L_n11_1_L_n11_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter4", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter4", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453.mac_muladd_8s_4s_7s_12_4_1_U97", "Parent" : "39"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453.flow_control_loop_pipe_sequential_init_U", "Parent" : "39"},
	{"ID" : "42", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463", "Parent" : "0", "Child" : ["43", "44"],
		"CDFG" : "case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "m27_19_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_data_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "sext_ln247", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_data_12", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "sext_ln22_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln241", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i12_i4097189_phi_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "m120_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln108", "Type" : "None", "Direction" : "I"},
			{"Name" : "m27_21_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "L_n12_1_L_n12_2_L_n12_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463.mul_8s_7s_9_1_1_U104", "Parent" : "42"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463.flow_control_loop_pipe_sequential_init_U", "Parent" : "42"},
	{"ID" : "45", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_4s_4s_8_1_1_U116", "Parent" : "0"},
	{"ID" : "46", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_5s_3s_5_1_1_U117", "Parent" : "0"}]}
