-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity case_3_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m27_2_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    in_data_12_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in_data_12_ce0 : OUT STD_LOGIC;
    in_data_12_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    conv_i3873_cast : IN STD_LOGIC_VECTOR (4 downto 0);
    sext_ln131 : IN STD_LOGIC_VECTOR (3 downto 0);
    sext_ln22 : IN STD_LOGIC_VECTOR (3 downto 0);
    m27_3_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    m27_3_out_ap_vld : OUT STD_LOGIC;
    m124_out : OUT STD_LOGIC_VECTOR (8 downto 0);
    m124_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of case_3_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv8_40 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln131_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln22_cast_fu_139_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln22_cast_reg_358 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln131_cast_fu_143_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln131_cast_reg_363 : STD_LOGIC_VECTOR (4 downto 0);
    signal conv_i3873_cast_cast_fu_147_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal conv_i3873_cast_cast_reg_368 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln131_reg_373 : STD_LOGIC_VECTOR (0 downto 0);
    signal m56_fu_274_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal m56_reg_382 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln133_fu_230_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal m124_fu_68 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal m27_3_fu_72 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal m27_fu_304_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_n4_2_fu_76 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln133_fu_235_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_i_n4_2_load : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten28_fu_80 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln132_fu_247_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten28_load : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten43_fu_84 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln131_fu_180_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten43_load : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal in_data_12_ce0_local : STD_LOGIC;
    signal icmp_ln132_fu_192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln133_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln22_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln22_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln22_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln22_fu_222_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln132_fu_241_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln138_fu_270_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln139_fu_287_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln139_fu_291_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln139_1_fu_295_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln139_1_fu_300_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component case_3_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component case_3_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_n4_2_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln131_fu_174_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_n4_2_fu_76 <= add_ln133_fu_235_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_n4_2_fu_76 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten28_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln131_fu_174_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten28_fu_80 <= select_ln132_fu_247_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten28_fu_80 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten43_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln131_fu_174_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten43_fu_84 <= add_ln131_fu_180_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten43_fu_84 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    m27_3_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    m27_3_fu_72 <= m27_2_reload;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    m27_3_fu_72 <= m27_fu_304_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                conv_i3873_cast_cast_reg_368 <= conv_i3873_cast_cast_fu_147_p1;
                icmp_ln131_reg_373 <= icmp_ln131_fu_174_p2;
                m56_reg_382 <= m56_fu_274_p2;
                sext_ln131_cast_reg_363 <= sext_ln131_cast_fu_143_p1;
                sext_ln22_cast_reg_358 <= sext_ln22_cast_fu_139_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                m124_fu_68 <= m56_fu_274_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln131_fu_180_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten43_load) + unsigned(ap_const_lv10_1));
    add_ln132_fu_241_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten28_load) + unsigned(ap_const_lv8_1));
    add_ln133_fu_235_p2 <= std_logic_vector(unsigned(select_ln22_fu_222_p3) + unsigned(ap_const_lv4_1));
    add_ln139_1_fu_295_p2 <= std_logic_vector(signed(sext_ln139_fu_291_p1) + signed(m56_reg_382));
    add_ln139_fu_287_p2 <= std_logic_vector(signed(sext_ln131_cast_reg_363) + signed(sext_ln22_cast_reg_358));
    and_ln22_fu_210_p2 <= (xor_ln22_fu_198_p2 and icmp_ln133_fu_204_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln131_fu_174_p2)
    begin
        if (((icmp_ln131_fu_174_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_n4_2_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_n4_2_fu_76)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_n4_2_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_n4_2_load <= i_n4_2_fu_76;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten28_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten28_fu_80)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten28_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten28_load <= indvar_flatten28_fu_80;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten43_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten43_fu_84)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten43_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten43_load <= indvar_flatten43_fu_84;
        end if; 
    end process;

        conv_i3873_cast_cast_fu_147_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv_i3873_cast),9));

    icmp_ln131_fu_174_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten43_load = ap_const_lv10_200) else "0";
    icmp_ln132_fu_192_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten28_load = ap_const_lv8_40) else "0";
    icmp_ln133_fu_204_p2 <= "1" when (ap_sig_allocacmp_i_n4_2_load = ap_const_lv4_8) else "0";
    in_data_12_address0 <= zext_ln133_fu_230_p1(4 - 1 downto 0);
    in_data_12_ce0 <= in_data_12_ce0_local;

    in_data_12_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_data_12_ce0_local <= ap_const_logic_1;
        else 
            in_data_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    m124_out <= m124_fu_68;

    m124_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln131_reg_373, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((icmp_ln131_reg_373 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            m124_out_ap_vld <= ap_const_logic_1;
        else 
            m124_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m27_3_out <= m27_3_fu_72;

    m27_3_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln131_reg_373, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((icmp_ln131_reg_373 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            m27_3_out_ap_vld <= ap_const_logic_1;
        else 
            m27_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m27_fu_304_p2 <= std_logic_vector(unsigned(m27_3_fu_72) + unsigned(sext_ln139_1_fu_300_p1));
    m56_fu_274_p2 <= std_logic_vector(signed(sext_ln138_fu_270_p1) + signed(conv_i3873_cast_cast_reg_368));
    or_ln22_fu_216_p2 <= (icmp_ln132_fu_192_p2 or and_ln22_fu_210_p2);
    select_ln132_fu_247_p3 <= 
        ap_const_lv8_1 when (icmp_ln132_fu_192_p2(0) = '1') else 
        add_ln132_fu_241_p2;
    select_ln22_fu_222_p3 <= 
        ap_const_lv4_0 when (or_ln22_fu_216_p2(0) = '1') else 
        ap_sig_allocacmp_i_n4_2_load;
        sext_ln131_cast_fu_143_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln131),5));

        sext_ln138_fu_270_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_data_12_q0),9));

        sext_ln139_1_fu_300_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln139_1_fu_295_p2),16));

        sext_ln139_fu_291_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln139_fu_287_p2),9));

        sext_ln22_cast_fu_139_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln22),5));

    xor_ln22_fu_198_p2 <= (icmp_ln132_fu_192_p2 xor ap_const_lv1_1);
    zext_ln133_fu_230_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln22_fu_222_p3),64));
end behav;
