// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module case_1_case_1_Pipeline_L_s2_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m18_19,
        in_data_16_address0,
        in_data_16_ce0,
        in_data_16_q0,
        in_data_12_address0,
        in_data_12_ce0,
        in_data_12_q0,
        in_data_14_address0,
        in_data_14_ce0,
        in_data_14_q0,
        conv25_i3788,
        m18_25_out_i,
        m18_25_out_o,
        m18_25_out_o_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] m18_19;
output  [4:0] in_data_16_address0;
output   in_data_16_ce0;
input  [2:0] in_data_16_q0;
output  [4:0] in_data_12_address0;
output   in_data_12_ce0;
input  [2:0] in_data_12_q0;
output  [4:0] in_data_14_address0;
output   in_data_14_ce0;
input  [2:0] in_data_14_q0;
input  [10:0] conv25_i3788;
input  [31:0] m18_25_out_i;
output  [31:0] m18_25_out_o;
output   m18_25_out_o_ap_vld;

reg ap_idle;
reg[31:0] m18_25_out_o;
reg m18_25_out_o_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln209_fu_133_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [5:0] m78_fu_165_p2;
reg  signed [5:0] m78_reg_243;
reg   [2:0] in_data_14_load_reg_248;
wire   [63:0] zext_ln209_fu_145_p1;
wire    ap_block_pp0_stage0;
wire   [31:0] m18_fu_200_p2;
wire    ap_loop_init;
reg   [5:0] i_s2_0_fu_64;
wire   [5:0] add_ln209_fu_139_p2;
reg   [5:0] ap_sig_allocacmp_i_s2_0_1;
reg    in_data_16_ce0_local;
reg    in_data_12_ce0_local;
reg    in_data_14_ce0_local;
wire  signed [10:0] sext_ln211_fu_175_p1;
wire  signed [10:0] m79_fu_178_p2;
wire  signed [11:0] sext_ln212_1_fu_186_p1;
wire  signed [11:0] sext_ln212_fu_183_p1;
wire   [11:0] add_ln212_fu_190_p2;
wire  signed [31:0] sext_ln212_2_fu_196_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_s2_0_fu_64 = 6'd0;
#0 ap_done_reg = 1'b0;
end

case_1_mul_3s_3s_6_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 6 ))
mul_3s_3s_6_1_1_U1(
    .din0(in_data_12_q0),
    .din1(in_data_16_q0),
    .dout(m78_fu_165_p2)
);

case_1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln209_fu_133_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_s2_0_fu_64 <= add_ln209_fu_139_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_s2_0_fu_64 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        in_data_14_load_reg_248 <= in_data_14_q0;
        m78_reg_243 <= m78_fu_165_p2;
    end
end

always @ (*) begin
    if (((icmp_ln209_fu_133_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_s2_0_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_s2_0_1 = i_s2_0_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_data_12_ce0_local = 1'b1;
    end else begin
        in_data_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_data_14_ce0_local = 1'b1;
    end else begin
        in_data_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_data_16_ce0_local = 1'b1;
    end else begin
        in_data_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            m18_25_out_o = m18_19;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            m18_25_out_o = m18_fu_200_p2;
        end else begin
            m18_25_out_o = m18_25_out_i;
        end
    end else begin
        m18_25_out_o = m18_25_out_i;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        m18_25_out_o_ap_vld = 1'b1;
    end else begin
        m18_25_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln209_fu_139_p2 = (ap_sig_allocacmp_i_s2_0_1 + 6'd1);

assign add_ln212_fu_190_p2 = ($signed(sext_ln212_1_fu_186_p1) + $signed(sext_ln212_fu_183_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln209_fu_133_p2 = ((ap_sig_allocacmp_i_s2_0_1 == 6'd32) ? 1'b1 : 1'b0);

assign in_data_12_address0 = zext_ln209_fu_145_p1;

assign in_data_12_ce0 = in_data_12_ce0_local;

assign in_data_14_address0 = zext_ln209_fu_145_p1;

assign in_data_14_ce0 = in_data_14_ce0_local;

assign in_data_16_address0 = zext_ln209_fu_145_p1;

assign in_data_16_ce0 = in_data_16_ce0_local;

assign m18_fu_200_p2 = ($signed(m18_25_out_i) + $signed(sext_ln212_2_fu_196_p1));

assign m79_fu_178_p2 = ($signed(sext_ln211_fu_175_p1) + $signed(conv25_i3788));

assign sext_ln211_fu_175_p1 = $signed(in_data_14_load_reg_248);

assign sext_ln212_1_fu_186_p1 = m79_fu_178_p2;

assign sext_ln212_2_fu_196_p1 = $signed(add_ln212_fu_190_p2);

assign sext_ln212_fu_183_p1 = m78_reg_243;

assign zext_ln209_fu_145_p1 = ap_sig_allocacmp_i_s2_0_1;

endmodule //case_1_case_1_Pipeline_L_s2_1
