// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="gemm_gemm,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.297000,HLS_SYN_LAT=4202625,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1302,HLS_SYN_LUT=1986,HLS_VERSION=2025_1}" *)

module gemm (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m1_address0,
        m1_ce0,
        m1_q0,
        m2_address0,
        m2_ce0,
        m2_q0,
        prod_address0,
        prod_ce0,
        prod_we0,
        prod_d0
);

parameter    ap_ST_fsm_state1 = 19'd1;
parameter    ap_ST_fsm_state2 = 19'd2;
parameter    ap_ST_fsm_state3 = 19'd4;
parameter    ap_ST_fsm_state4 = 19'd8;
parameter    ap_ST_fsm_state5 = 19'd16;
parameter    ap_ST_fsm_state6 = 19'd32;
parameter    ap_ST_fsm_state7 = 19'd64;
parameter    ap_ST_fsm_state8 = 19'd128;
parameter    ap_ST_fsm_state9 = 19'd256;
parameter    ap_ST_fsm_state10 = 19'd512;
parameter    ap_ST_fsm_state11 = 19'd1024;
parameter    ap_ST_fsm_state12 = 19'd2048;
parameter    ap_ST_fsm_state13 = 19'd4096;
parameter    ap_ST_fsm_state14 = 19'd8192;
parameter    ap_ST_fsm_state15 = 19'd16384;
parameter    ap_ST_fsm_state16 = 19'd32768;
parameter    ap_ST_fsm_state17 = 19'd65536;
parameter    ap_ST_fsm_state18 = 19'd131072;
parameter    ap_ST_fsm_state19 = 19'd262144;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] m1_address0;
output   m1_ce0;
input  [63:0] m1_q0;
output  [11:0] m2_address0;
output   m2_ce0;
input  [63:0] m2_q0;
output  [11:0] prod_address0;
output   prod_ce0;
output   prod_we0;
output  [63:0] prod_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [18:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [6:0] add_ln8_fu_152_p2;
reg   [6:0] add_ln8_reg_270;
wire    ap_CS_fsm_state2;
wire   [11:0] tmp_1_fu_162_p3;
reg   [11:0] tmp_1_reg_275;
wire   [6:0] add_ln9_fu_176_p2;
reg   [6:0] add_ln9_reg_284;
wire    ap_CS_fsm_state3;
wire   [11:0] zext_ln9_fu_182_p1;
reg   [11:0] zext_ln9_reg_289;
wire   [6:0] add_ln12_fu_196_p2;
reg   [6:0] add_ln12_reg_298;
wire    ap_CS_fsm_state4;
reg   [63:0] m1_load_reg_313;
wire    ap_CS_fsm_state5;
reg   [63:0] m2_load_reg_318;
wire    ap_CS_fsm_state6;
wire   [63:0] grp_fu_134_p2;
reg   [63:0] mult_reg_333;
wire    ap_CS_fsm_state12;
wire   [63:0] grp_fu_129_p2;
wire    ap_CS_fsm_state19;
reg   [6:0] j_reg_95;
wire   [0:0] icmp_ln8_fu_146_p2;
wire   [0:0] icmp_ln12_fu_190_p2;
reg   [6:0] k_reg_106;
wire   [0:0] icmp_ln9_fu_170_p2;
reg   [63:0] sum_reg_117;
wire   [63:0] zext_ln14_fu_223_p1;
wire   [63:0] zext_ln14_1_fu_233_p1;
wire   [63:0] zext_ln17_fu_242_p1;
reg   [6:0] i_fu_52;
reg    m1_ce0_local;
reg    m2_ce0_local;
reg    prod_we0_local;
wire   [63:0] bitcast_ln17_fu_247_p1;
reg    prod_ce0_local;
wire    ap_CS_fsm_state13;
wire   [63:0] grp_fu_134_p0;
wire   [63:0] grp_fu_134_p1;
wire   [5:0] empty_fu_158_p1;
wire   [5:0] trunc_ln13_fu_206_p1;
wire   [11:0] zext_ln12_fu_202_p1;
wire   [11:0] add_ln14_fu_218_p2;
wire   [11:0] shl_ln_fu_210_p3;
wire   [11:0] add_ln14_1_fu_228_p2;
wire   [11:0] add_ln17_fu_238_p2;
reg   [18:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 19'd1;
#0 i_fu_52 = 7'd0;
end

gemm_dadd_64ns_64ns_64_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_7_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_reg_117),
    .din1(mult_reg_333),
    .ce(1'b1),
    .dout(grp_fu_129_p2)
);

gemm_dmul_64ns_64ns_64_7_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_7_max_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_134_p0),
    .din1(grp_fu_134_p1),
    .ce(1'b1),
    .dout(grp_fu_134_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_52 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln9_fu_170_p2 == 1'd1))) begin
        i_fu_52 <= add_ln8_reg_270;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln12_fu_190_p2 == 1'd1))) begin
        j_reg_95 <= add_ln9_reg_284;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln8_fu_146_p2 == 1'd0))) begin
        j_reg_95 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        k_reg_106 <= add_ln12_reg_298;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln9_fu_170_p2 == 1'd0))) begin
        k_reg_106 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        sum_reg_117 <= grp_fu_129_p2;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln9_fu_170_p2 == 1'd0))) begin
        sum_reg_117 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln12_reg_298 <= add_ln12_fu_196_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln8_reg_270 <= add_ln8_fu_152_p2;
        tmp_1_reg_275[11 : 6] <= tmp_1_fu_162_p3[11 : 6];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln9_reg_284 <= add_ln9_fu_176_p2;
        zext_ln9_reg_289[6 : 0] <= zext_ln9_fu_182_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        m1_load_reg_313 <= m1_q0;
        m2_load_reg_318 <= m2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        mult_reg_333 <= grp_fu_134_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln8_fu_146_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln8_fu_146_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        m1_ce0_local = 1'b1;
    end else begin
        m1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        m2_ce0_local = 1'b1;
    end else begin
        m2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        prod_ce0_local = 1'b1;
    end else begin
        prod_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln12_fu_190_p2 == 1'd1))) begin
        prod_we0_local = 1'b1;
    end else begin
        prod_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln8_fu_146_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln9_fu_170_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln12_fu_190_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln12_fu_196_p2 = (k_reg_106 + 7'd1);

assign add_ln14_1_fu_228_p2 = (shl_ln_fu_210_p3 + zext_ln9_reg_289);

assign add_ln14_fu_218_p2 = (zext_ln12_fu_202_p1 + tmp_1_reg_275);

assign add_ln17_fu_238_p2 = (zext_ln9_reg_289 + tmp_1_reg_275);

assign add_ln8_fu_152_p2 = (i_fu_52 + 7'd1);

assign add_ln9_fu_176_p2 = (j_reg_95 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign bitcast_ln17_fu_247_p1 = sum_reg_117;

assign empty_fu_158_p1 = i_fu_52[5:0];

assign grp_fu_134_p0 = m1_load_reg_313;

assign grp_fu_134_p1 = m2_load_reg_318;

assign icmp_ln12_fu_190_p2 = ((k_reg_106 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln8_fu_146_p2 = ((i_fu_52 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_170_p2 = ((j_reg_95 == 7'd64) ? 1'b1 : 1'b0);

assign m1_address0 = zext_ln14_fu_223_p1;

assign m1_ce0 = m1_ce0_local;

assign m2_address0 = zext_ln14_1_fu_233_p1;

assign m2_ce0 = m2_ce0_local;

assign prod_address0 = zext_ln17_fu_242_p1;

assign prod_ce0 = prod_ce0_local;

assign prod_d0 = bitcast_ln17_fu_247_p1;

assign prod_we0 = prod_we0_local;

assign shl_ln_fu_210_p3 = {{trunc_ln13_fu_206_p1}, {6'd0}};

assign tmp_1_fu_162_p3 = {{empty_fu_158_p1}, {6'd0}};

assign trunc_ln13_fu_206_p1 = k_reg_106[5:0];

assign zext_ln12_fu_202_p1 = k_reg_106;

assign zext_ln14_1_fu_233_p1 = add_ln14_1_fu_228_p2;

assign zext_ln14_fu_223_p1 = add_ln14_fu_218_p2;

assign zext_ln17_fu_242_p1 = add_ln17_fu_238_p2;

assign zext_ln9_fu_182_p1 = j_reg_95;

always @ (posedge ap_clk) begin
    tmp_1_reg_275[5:0] <= 6'b000000;
    zext_ln9_reg_289[11:7] <= 5'b00000;
end

endmodule //gemm
