// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module case_3_case_3_Pipeline_L_n3_1_L_n3_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m27_1_reload,
        in_data_0_address0,
        in_data_0_ce0,
        in_data_0_q0,
        in_data_6_address0,
        in_data_6_ce0,
        in_data_6_q0,
        in_data_10_address0,
        in_data_10_ce0,
        in_data_10_q0,
        in_data_2_address0,
        in_data_2_ce0,
        in_data_2_q0,
        in_data_14_address0,
        in_data_14_ce0,
        in_data_14_q0,
        in_scalar_load_2_cast,
        in_data_8_address0,
        in_data_8_ce0,
        in_data_8_q0,
        in_data_4_address0,
        in_data_4_ce0,
        in_data_4_q0,
        m43_cast70,
        mul_i4971_cast,
        sext_ln108_1,
        m27_2_out,
        m27_2_out_ap_vld,
        add_i5025_phi_out,
        add_i5025_phi_out_ap_vld,
        add_i4863_phi_out,
        add_i4863_phi_out_ap_vld,
        phi_ln127_out,
        phi_ln127_out_ap_vld,
        conv3_i_i4798204_phi_out,
        conv3_i_i4798204_phi_out_ap_vld,
        add_i4277_phi_out,
        add_i4277_phi_out_ap_vld,
        conv3_i12_i4097189_phi_out,
        conv3_i12_i4097189_phi_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] m27_1_reload;
output  [3:0] in_data_0_address0;
output   in_data_0_ce0;
input  [7:0] in_data_0_q0;
output  [3:0] in_data_6_address0;
output   in_data_6_ce0;
input  [7:0] in_data_6_q0;
output  [3:0] in_data_10_address0;
output   in_data_10_ce0;
input  [7:0] in_data_10_q0;
output  [3:0] in_data_2_address0;
output   in_data_2_ce0;
input  [7:0] in_data_2_q0;
output  [3:0] in_data_14_address0;
output   in_data_14_ce0;
input  [7:0] in_data_14_q0;
input  [3:0] in_scalar_load_2_cast;
output  [3:0] in_data_8_address0;
output   in_data_8_ce0;
input  [7:0] in_data_8_q0;
output  [3:0] in_data_4_address0;
output   in_data_4_ce0;
input  [7:0] in_data_4_q0;
input  [4:0] m43_cast70;
input  [7:0] mul_i4971_cast;
input  [3:0] sext_ln108_1;
output  [15:0] m27_2_out;
output   m27_2_out_ap_vld;
output  [8:0] add_i5025_phi_out;
output   add_i5025_phi_out_ap_vld;
output  [8:0] add_i4863_phi_out;
output   add_i4863_phi_out_ap_vld;
output  [2:0] phi_ln127_out;
output   phi_ln127_out_ap_vld;
output  [8:0] conv3_i_i4798204_phi_out;
output   conv3_i_i4798204_phi_out_ap_vld;
output  [7:0] add_i4277_phi_out;
output   add_i4277_phi_out_ap_vld;
output  [2:0] conv3_i12_i4097189_phi_out;
output   conv3_i12_i4097189_phi_out_ap_vld;

reg ap_idle;
reg m27_2_out_ap_vld;
reg add_i5025_phi_out_ap_vld;
reg add_i4863_phi_out_ap_vld;
reg phi_ln127_out_ap_vld;
reg conv3_i_i4798204_phi_out_ap_vld;
reg add_i4277_phi_out_ap_vld;
reg conv3_i12_i4097189_phi_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln108_fu_322_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [4:0] sext_ln108_1_cast_fu_288_p1;
reg  signed [4:0] sext_ln108_1_cast_reg_628;
wire  signed [8:0] mul_i4971_cast_cast_fu_292_p1;
reg  signed [8:0] mul_i4971_cast_cast_reg_633;
wire  signed [7:0] in_scalar_load_2_cast_cast_fu_296_p1;
reg  signed [7:0] in_scalar_load_2_cast_cast_reg_638;
wire  signed [9:0] m43_cast70_cast_fu_300_p1;
reg  signed [9:0] m43_cast70_cast_reg_643;
reg   [0:0] icmp_ln108_reg_648;
reg   [0:0] icmp_ln108_reg_648_pp0_iter1_reg;
wire   [63:0] zext_ln109_fu_351_p1;
reg   [63:0] zext_ln109_reg_652;
reg  signed [7:0] m39_reg_679;
reg  signed [7:0] in_data_10_load_reg_689;
wire   [4:0] m46_fu_383_p2;
reg   [4:0] m46_reg_699;
wire   [3:0] add_ln128_5_fu_405_p2;
reg   [3:0] add_ln128_5_reg_709;
wire   [9:0] add_ln128_fu_462_p2;
reg   [9:0] add_ln128_reg_714;
wire   [9:0] add_ln128_2_fu_476_p2;
reg   [9:0] add_ln128_2_reg_719;
wire   [8:0] add_ln128_7_fu_500_p2;
reg   [8:0] add_ln128_7_reg_724;
wire    ap_block_pp0_stage0;
reg   [7:0] add_i4277_phi_fu_90;
wire  signed [7:0] m47_fu_453_p2;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [2:0] phi_ln127_fu_94;
wire  signed [2:0] m49_fu_393_p1;
reg   [8:0] add_i4863_phi_fu_98;
wire  signed [8:0] m40_fu_436_p2;
reg   [8:0] add_i5025_phi_fu_102;
wire  signed [8:0] m37_fu_423_p2;
reg   [15:0] m27_2_fu_106;
wire   [15:0] m27_fu_549_p2;
wire    ap_loop_init;
reg   [3:0] i_n3_1_fu_110;
wire   [3:0] add_ln109_fu_359_p2;
reg   [3:0] ap_sig_allocacmp_i_n3_1_load;
reg   [6:0] indvar_flatten21_fu_114;
wire   [6:0] add_ln108_fu_328_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten21_load;
wire    ap_block_pp0_stage0_01001;
reg    in_data_0_ce0_local;
reg    in_data_10_ce0_local;
reg    in_data_8_ce0_local;
reg    in_data_4_ce0_local;
reg    in_data_6_ce0_local;
reg    in_data_2_ce0_local;
reg    in_data_14_ce0_local;
wire   [0:0] icmp_ln109_fu_337_p2;
wire   [3:0] select_ln22_fu_343_p3;
wire  signed [7:0] trunc_ln122_fu_375_p0;
wire  signed [7:0] trunc_ln122_1_fu_379_p0;
wire  signed [4:0] m46_fu_383_p0;
wire  signed [4:0] m46_fu_383_p1;
wire   [1:0] m48_fu_389_p1;
wire  signed [3:0] sext_ln128_1_fu_401_p1;
wire  signed [3:0] sext_ln128_fu_397_p1;
wire  signed [8:0] sext_ln110_1_fu_419_p1;
wire  signed [8:0] sext_ln110_fu_416_p1;
wire  signed [8:0] sext_ln113_1_fu_432_p1;
wire  signed [8:0] sext_ln113_fu_429_p1;
wire  signed [9:0] sext_ln122_fu_446_p1;
wire   [8:0] add_ln128_1_fu_467_p2;
wire  signed [9:0] sext_ln128_3_fu_472_p1;
wire  signed [9:0] sext_ln114_fu_442_p1;
wire  signed [8:0] sext_ln126_fu_458_p1;
wire  signed [8:0] sext_ln124_fu_450_p1;
wire  signed [4:0] sext_ln128_5_fu_488_p1;
wire   [4:0] add_ln128_6_fu_491_p2;
wire  signed [8:0] sext_ln128_6_fu_496_p1;
wire   [8:0] add_ln128_4_fu_482_p2;
wire  signed [10:0] sext_ln128_4_fu_527_p1;
wire  signed [10:0] sext_ln128_2_fu_524_p1;
wire  signed [10:0] sext_ln128_7_fu_536_p1;
wire   [10:0] add_ln128_3_fu_530_p2;
wire   [10:0] add_ln128_8_fu_539_p2;
wire  signed [15:0] sext_ln128_8_fu_545_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 add_i4277_phi_fu_90 = 8'd0;
#0 phi_ln127_fu_94 = 3'd0;
#0 add_i4863_phi_fu_98 = 9'd0;
#0 add_i5025_phi_fu_102 = 9'd0;
#0 m27_2_fu_106 = 16'd0;
#0 i_n3_1_fu_110 = 4'd0;
#0 indvar_flatten21_fu_114 = 7'd0;
#0 ap_done_reg = 1'b0;
end

case_3_mul_5s_5s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 5 ))
mul_5s_5s_5_1_1_U8(
    .din0(m46_fu_383_p0),
    .din1(m46_fu_383_p1),
    .dout(m46_fu_383_p2)
);

case_3_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln108_fu_322_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_n3_1_fu_110 <= add_ln109_fu_359_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_n3_1_fu_110 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln108_fu_322_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten21_fu_114 <= add_ln108_fu_328_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten21_fu_114 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            m27_2_fu_106 <= m27_1_reload;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            m27_2_fu_106 <= m27_fu_549_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        add_i4277_phi_fu_90 <= m47_fu_453_p2;
        add_i4863_phi_fu_98 <= m40_fu_436_p2;
        add_i5025_phi_fu_102 <= m37_fu_423_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln128_2_reg_719 <= add_ln128_2_fu_476_p2;
        add_ln128_7_reg_724 <= add_ln128_7_fu_500_p2;
        add_ln128_reg_714 <= add_ln128_fu_462_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln128_5_reg_709 <= add_ln128_5_fu_405_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln108_reg_648 <= icmp_ln108_fu_322_p2;
        icmp_ln108_reg_648_pp0_iter1_reg <= icmp_ln108_reg_648;
        in_data_10_load_reg_689 <= in_data_10_q0;
        in_scalar_load_2_cast_cast_reg_638 <= in_scalar_load_2_cast_cast_fu_296_p1;
        m39_reg_679 <= in_data_0_q0;
        m43_cast70_cast_reg_643 <= m43_cast70_cast_fu_300_p1;
        m46_reg_699 <= m46_fu_383_p2;
        mul_i4971_cast_cast_reg_633 <= mul_i4971_cast_cast_fu_292_p1;
        sext_ln108_1_cast_reg_628 <= sext_ln108_1_cast_fu_288_p1;
        zext_ln109_reg_652[3 : 0] <= zext_ln109_fu_351_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        phi_ln127_fu_94 <= m49_fu_393_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln108_reg_648_pp0_iter1_reg == 1'd1))) begin
        add_i4277_phi_out_ap_vld = 1'b1;
    end else begin
        add_i4277_phi_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln108_reg_648_pp0_iter1_reg == 1'd1))) begin
        add_i4863_phi_out_ap_vld = 1'b1;
    end else begin
        add_i4863_phi_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln108_reg_648_pp0_iter1_reg == 1'd1))) begin
        add_i5025_phi_out_ap_vld = 1'b1;
    end else begin
        add_i5025_phi_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln108_fu_322_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_n3_1_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i_n3_1_load = i_n3_1_fu_110;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten21_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten21_load = indvar_flatten21_fu_114;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln108_reg_648_pp0_iter1_reg == 1'd1))) begin
        conv3_i12_i4097189_phi_out_ap_vld = 1'b1;
    end else begin
        conv3_i12_i4097189_phi_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln108_reg_648_pp0_iter1_reg == 1'd1))) begin
        conv3_i_i4798204_phi_out_ap_vld = 1'b1;
    end else begin
        conv3_i_i4798204_phi_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_data_0_ce0_local = 1'b1;
    end else begin
        in_data_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_data_10_ce0_local = 1'b1;
    end else begin
        in_data_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_data_14_ce0_local = 1'b1;
    end else begin
        in_data_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_data_2_ce0_local = 1'b1;
    end else begin
        in_data_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_data_4_ce0_local = 1'b1;
    end else begin
        in_data_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_data_6_ce0_local = 1'b1;
    end else begin
        in_data_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_data_8_ce0_local = 1'b1;
    end else begin
        in_data_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln108_reg_648_pp0_iter1_reg == 1'd1))) begin
        m27_2_out_ap_vld = 1'b1;
    end else begin
        m27_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln108_reg_648_pp0_iter1_reg == 1'd1))) begin
        phi_ln127_out_ap_vld = 1'b1;
    end else begin
        phi_ln127_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_i4277_phi_out = add_i4277_phi_fu_90;

assign add_i4863_phi_out = add_i4863_phi_fu_98;

assign add_i5025_phi_out = add_i5025_phi_fu_102;

assign add_ln108_fu_328_p2 = (ap_sig_allocacmp_indvar_flatten21_load + 7'd1);

assign add_ln109_fu_359_p2 = (select_ln22_fu_343_p3 + 4'd1);

assign add_ln128_1_fu_467_p2 = ($signed(mul_i4971_cast_cast_reg_633) + $signed(sext_ln110_fu_416_p1));

assign add_ln128_2_fu_476_p2 = ($signed(sext_ln128_3_fu_472_p1) + $signed(sext_ln114_fu_442_p1));

assign add_ln128_3_fu_530_p2 = ($signed(sext_ln128_4_fu_527_p1) + $signed(sext_ln128_2_fu_524_p1));

assign add_ln128_4_fu_482_p2 = ($signed(sext_ln126_fu_458_p1) + $signed(sext_ln124_fu_450_p1));

assign add_ln128_5_fu_405_p2 = ($signed(sext_ln128_1_fu_401_p1) + $signed(sext_ln128_fu_397_p1));

assign add_ln128_6_fu_491_p2 = ($signed(sext_ln128_5_fu_488_p1) + $signed(sext_ln108_1_cast_reg_628));

assign add_ln128_7_fu_500_p2 = ($signed(sext_ln128_6_fu_496_p1) + $signed(add_ln128_4_fu_482_p2));

assign add_ln128_8_fu_539_p2 = ($signed(sext_ln128_7_fu_536_p1) + $signed(add_ln128_3_fu_530_p2));

assign add_ln128_fu_462_p2 = ($signed(m43_cast70_cast_reg_643) + $signed(sext_ln122_fu_446_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign conv3_i12_i4097189_phi_out = phi_ln127_fu_94;

assign conv3_i_i4798204_phi_out = add_i5025_phi_fu_102;

assign icmp_ln108_fu_322_p2 = ((ap_sig_allocacmp_indvar_flatten21_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_337_p2 = ((ap_sig_allocacmp_i_n3_1_load == 4'd8) ? 1'b1 : 1'b0);

assign in_data_0_address0 = zext_ln109_fu_351_p1;

assign in_data_0_ce0 = in_data_0_ce0_local;

assign in_data_10_address0 = zext_ln109_fu_351_p1;

assign in_data_10_ce0 = in_data_10_ce0_local;

assign in_data_14_address0 = zext_ln109_reg_652;

assign in_data_14_ce0 = in_data_14_ce0_local;

assign in_data_2_address0 = zext_ln109_reg_652;

assign in_data_2_ce0 = in_data_2_ce0_local;

assign in_data_4_address0 = zext_ln109_fu_351_p1;

assign in_data_4_ce0 = in_data_4_ce0_local;

assign in_data_6_address0 = zext_ln109_reg_652;

assign in_data_6_ce0 = in_data_6_ce0_local;

assign in_data_8_address0 = zext_ln109_fu_351_p1;

assign in_data_8_ce0 = in_data_8_ce0_local;

assign in_scalar_load_2_cast_cast_fu_296_p1 = $signed(in_scalar_load_2_cast);

assign m27_2_out = m27_2_fu_106;

assign m27_fu_549_p2 = ($signed(m27_2_fu_106) + $signed(sext_ln128_8_fu_545_p1));

assign m37_fu_423_p2 = ($signed(sext_ln110_1_fu_419_p1) + $signed(sext_ln110_fu_416_p1));

assign m40_fu_436_p2 = ($signed(sext_ln113_1_fu_432_p1) + $signed(sext_ln113_fu_429_p1));

assign m43_cast70_cast_fu_300_p1 = $signed(m43_cast70);

assign m46_fu_383_p0 = trunc_ln122_1_fu_379_p0[4:0];

assign m46_fu_383_p1 = trunc_ln122_fu_375_p0[4:0];

assign m47_fu_453_p2 = ($signed(in_data_14_q0) + $signed(in_scalar_load_2_cast_cast_reg_638));

assign m48_fu_389_p1 = in_data_8_q0[1:0];

assign m49_fu_393_p1 = in_data_4_q0[2:0];

assign mul_i4971_cast_cast_fu_292_p1 = $signed(mul_i4971_cast);

assign phi_ln127_out = phi_ln127_fu_94;

assign select_ln22_fu_343_p3 = ((icmp_ln109_fu_337_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_i_n3_1_load);

assign sext_ln108_1_cast_fu_288_p1 = $signed(sext_ln108_1);

assign sext_ln110_1_fu_419_p1 = $signed(in_data_6_q0);

assign sext_ln110_fu_416_p1 = m39_reg_679;

assign sext_ln113_1_fu_432_p1 = $signed(in_data_2_q0);

assign sext_ln113_fu_429_p1 = in_data_10_load_reg_689;

assign sext_ln114_fu_442_p1 = m37_fu_423_p2;

assign sext_ln122_fu_446_p1 = m40_fu_436_p2;

assign sext_ln124_fu_450_p1 = $signed(m46_reg_699);

assign sext_ln126_fu_458_p1 = m47_fu_453_p2;

assign sext_ln128_1_fu_401_p1 = m49_fu_393_p1;

assign sext_ln128_2_fu_524_p1 = $signed(add_ln128_reg_714);

assign sext_ln128_3_fu_472_p1 = $signed(add_ln128_1_fu_467_p2);

assign sext_ln128_4_fu_527_p1 = $signed(add_ln128_2_reg_719);

assign sext_ln128_5_fu_488_p1 = $signed(add_ln128_5_reg_709);

assign sext_ln128_6_fu_496_p1 = $signed(add_ln128_6_fu_491_p2);

assign sext_ln128_7_fu_536_p1 = $signed(add_ln128_7_reg_724);

assign sext_ln128_8_fu_545_p1 = $signed(add_ln128_8_fu_539_p2);

assign sext_ln128_fu_397_p1 = $signed(m48_fu_389_p1);

assign trunc_ln122_1_fu_379_p0 = in_data_10_q0;

assign trunc_ln122_fu_375_p0 = in_data_0_q0;

assign zext_ln109_fu_351_p1 = select_ln22_fu_343_p3;

always @ (posedge ap_clk) begin
    zext_ln109_reg_652[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //case_3_case_3_Pipeline_L_n3_1_L_n3_2
