// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="case_3_case_3,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=12.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.319000,HLS_SYN_LAT=3157,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1611,HLS_SYN_LUT=4558,HLS_VERSION=2025_1}" *)

module case_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_data_0_address0,
        in_data_0_ce0,
        in_data_0_q0,
        in_data_0_address1,
        in_data_0_ce1,
        in_data_0_q1,
        in_data_1_address0,
        in_data_1_ce0,
        in_data_1_we0,
        in_data_1_d0,
        in_data_1_q0,
        in_data_1_address1,
        in_data_1_ce1,
        in_data_1_we1,
        in_data_1_d1,
        in_data_1_q1,
        in_data_2_address0,
        in_data_2_ce0,
        in_data_2_q0,
        in_data_2_address1,
        in_data_2_ce1,
        in_data_2_q1,
        in_data_3_address0,
        in_data_3_ce0,
        in_data_3_we0,
        in_data_3_d0,
        in_data_3_q0,
        in_data_3_address1,
        in_data_3_ce1,
        in_data_3_we1,
        in_data_3_d1,
        in_data_3_q1,
        in_data_4_address0,
        in_data_4_ce0,
        in_data_4_q0,
        in_data_5_address0,
        in_data_5_ce0,
        in_data_5_we0,
        in_data_5_d0,
        in_data_5_q0,
        in_data_5_address1,
        in_data_5_ce1,
        in_data_5_we1,
        in_data_5_d1,
        in_data_5_q1,
        in_data_6_address0,
        in_data_6_ce0,
        in_data_6_q0,
        in_data_7_address0,
        in_data_7_ce0,
        in_data_7_we0,
        in_data_7_d0,
        in_data_7_q0,
        in_data_7_address1,
        in_data_7_ce1,
        in_data_7_we1,
        in_data_7_d1,
        in_data_7_q1,
        in_data_8_address0,
        in_data_8_ce0,
        in_data_8_q0,
        in_data_9_address0,
        in_data_9_ce0,
        in_data_9_we0,
        in_data_9_d0,
        in_data_9_q0,
        in_data_9_address1,
        in_data_9_ce1,
        in_data_9_we1,
        in_data_9_d1,
        in_data_9_q1,
        in_data_10_address0,
        in_data_10_ce0,
        in_data_10_q0,
        in_data_11_address0,
        in_data_11_ce0,
        in_data_11_we0,
        in_data_11_d0,
        in_data_11_q0,
        in_data_11_address1,
        in_data_11_ce1,
        in_data_11_we1,
        in_data_11_d1,
        in_data_11_q1,
        in_data_12_address0,
        in_data_12_ce0,
        in_data_12_q0,
        in_data_13_address0,
        in_data_13_ce0,
        in_data_13_we0,
        in_data_13_d0,
        in_data_13_q0,
        in_data_13_address1,
        in_data_13_ce1,
        in_data_13_we1,
        in_data_13_d1,
        in_data_13_q1,
        in_data_14_address0,
        in_data_14_ce0,
        in_data_14_q0,
        in_data_15_address0,
        in_data_15_ce0,
        in_data_15_we0,
        in_data_15_d0,
        in_data_15_q0,
        in_data_15_address1,
        in_data_15_ce1,
        in_data_15_we1,
        in_data_15_d1,
        in_data_15_q1,
        in_scalar_address0,
        in_scalar_ce0,
        in_scalar_q0,
        in_scalar_address1,
        in_scalar_ce1,
        in_scalar_q1,
        out_data_0,
        out_data_1,
        out_data_2,
        out_data_3
);

parameter    ap_ST_fsm_state1 = 27'd1;
parameter    ap_ST_fsm_state2 = 27'd2;
parameter    ap_ST_fsm_state3 = 27'd4;
parameter    ap_ST_fsm_state4 = 27'd8;
parameter    ap_ST_fsm_state5 = 27'd16;
parameter    ap_ST_fsm_state6 = 27'd32;
parameter    ap_ST_fsm_state7 = 27'd64;
parameter    ap_ST_fsm_state8 = 27'd128;
parameter    ap_ST_fsm_state9 = 27'd256;
parameter    ap_ST_fsm_state10 = 27'd512;
parameter    ap_ST_fsm_state11 = 27'd1024;
parameter    ap_ST_fsm_state12 = 27'd2048;
parameter    ap_ST_fsm_state13 = 27'd4096;
parameter    ap_ST_fsm_state14 = 27'd8192;
parameter    ap_ST_fsm_state15 = 27'd16384;
parameter    ap_ST_fsm_state16 = 27'd32768;
parameter    ap_ST_fsm_state17 = 27'd65536;
parameter    ap_ST_fsm_state18 = 27'd131072;
parameter    ap_ST_fsm_state19 = 27'd262144;
parameter    ap_ST_fsm_state20 = 27'd524288;
parameter    ap_ST_fsm_state21 = 27'd1048576;
parameter    ap_ST_fsm_state22 = 27'd2097152;
parameter    ap_ST_fsm_state23 = 27'd4194304;
parameter    ap_ST_fsm_state24 = 27'd8388608;
parameter    ap_ST_fsm_state25 = 27'd16777216;
parameter    ap_ST_fsm_state26 = 27'd33554432;
parameter    ap_ST_fsm_state27 = 27'd67108864;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] in_data_0_address0;
output   in_data_0_ce0;
input  [7:0] in_data_0_q0;
output  [3:0] in_data_0_address1;
output   in_data_0_ce1;
input  [7:0] in_data_0_q1;
output  [3:0] in_data_1_address0;
output   in_data_1_ce0;
output   in_data_1_we0;
output  [7:0] in_data_1_d0;
input  [7:0] in_data_1_q0;
output  [3:0] in_data_1_address1;
output   in_data_1_ce1;
output   in_data_1_we1;
output  [7:0] in_data_1_d1;
input  [7:0] in_data_1_q1;
output  [3:0] in_data_2_address0;
output   in_data_2_ce0;
input  [7:0] in_data_2_q0;
output  [3:0] in_data_2_address1;
output   in_data_2_ce1;
input  [7:0] in_data_2_q1;
output  [3:0] in_data_3_address0;
output   in_data_3_ce0;
output   in_data_3_we0;
output  [7:0] in_data_3_d0;
input  [7:0] in_data_3_q0;
output  [3:0] in_data_3_address1;
output   in_data_3_ce1;
output   in_data_3_we1;
output  [7:0] in_data_3_d1;
input  [7:0] in_data_3_q1;
output  [3:0] in_data_4_address0;
output   in_data_4_ce0;
input  [7:0] in_data_4_q0;
output  [3:0] in_data_5_address0;
output   in_data_5_ce0;
output   in_data_5_we0;
output  [7:0] in_data_5_d0;
input  [7:0] in_data_5_q0;
output  [3:0] in_data_5_address1;
output   in_data_5_ce1;
output   in_data_5_we1;
output  [7:0] in_data_5_d1;
input  [7:0] in_data_5_q1;
output  [3:0] in_data_6_address0;
output   in_data_6_ce0;
input  [7:0] in_data_6_q0;
output  [3:0] in_data_7_address0;
output   in_data_7_ce0;
output   in_data_7_we0;
output  [7:0] in_data_7_d0;
input  [7:0] in_data_7_q0;
output  [3:0] in_data_7_address1;
output   in_data_7_ce1;
output   in_data_7_we1;
output  [7:0] in_data_7_d1;
input  [7:0] in_data_7_q1;
output  [3:0] in_data_8_address0;
output   in_data_8_ce0;
input  [7:0] in_data_8_q0;
output  [3:0] in_data_9_address0;
output   in_data_9_ce0;
output   in_data_9_we0;
output  [7:0] in_data_9_d0;
input  [7:0] in_data_9_q0;
output  [3:0] in_data_9_address1;
output   in_data_9_ce1;
output   in_data_9_we1;
output  [7:0] in_data_9_d1;
input  [7:0] in_data_9_q1;
output  [3:0] in_data_10_address0;
output   in_data_10_ce0;
input  [7:0] in_data_10_q0;
output  [3:0] in_data_11_address0;
output   in_data_11_ce0;
output   in_data_11_we0;
output  [7:0] in_data_11_d0;
input  [7:0] in_data_11_q0;
output  [3:0] in_data_11_address1;
output   in_data_11_ce1;
output   in_data_11_we1;
output  [7:0] in_data_11_d1;
input  [7:0] in_data_11_q1;
output  [3:0] in_data_12_address0;
output   in_data_12_ce0;
input  [7:0] in_data_12_q0;
output  [3:0] in_data_13_address0;
output   in_data_13_ce0;
output   in_data_13_we0;
output  [7:0] in_data_13_d0;
input  [7:0] in_data_13_q0;
output  [3:0] in_data_13_address1;
output   in_data_13_ce1;
output   in_data_13_we1;
output  [7:0] in_data_13_d1;
input  [7:0] in_data_13_q1;
output  [3:0] in_data_14_address0;
output   in_data_14_ce0;
input  [7:0] in_data_14_q0;
output  [3:0] in_data_15_address0;
output   in_data_15_ce0;
output   in_data_15_we0;
output  [7:0] in_data_15_d0;
input  [7:0] in_data_15_q0;
output  [3:0] in_data_15_address1;
output   in_data_15_ce1;
output   in_data_15_we1;
output  [7:0] in_data_15_d1;
input  [7:0] in_data_15_q1;
output  [4:0] in_scalar_address0;
output   in_scalar_ce0;
input  [3:0] in_scalar_q0;
output  [4:0] in_scalar_address1;
output   in_scalar_ce1;
input  [3:0] in_scalar_q1;
output  [7:0] out_data_0;
output  [7:0] out_data_1;
output  [7:0] out_data_2;
output  [7:0] out_data_3;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] in_data_0_address0;
reg in_data_0_ce0;
reg in_data_0_ce1;
reg[3:0] in_data_2_address0;
reg in_data_2_ce0;
reg in_data_2_ce1;
reg[3:0] in_data_4_address0;
reg in_data_4_ce0;
reg[3:0] in_data_6_address0;
reg in_data_6_ce0;
reg[3:0] in_data_8_address0;
reg in_data_8_ce0;
reg[3:0] in_data_12_address0;
reg in_data_12_ce0;
reg[3:0] in_data_14_address0;
reg in_data_14_ce0;

(* fsm_encoding = "none" *) reg   [26:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] reg_479;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_done;
reg   [3:0] in_scalar_load_reg_872;
wire   [9:0] shl_ln_fu_486_p3;
reg   [9:0] shl_ln_reg_878;
wire   [7:0] m38_fu_503_p2;
reg   [7:0] m38_reg_898;
wire    ap_CS_fsm_state4;
reg   [3:0] in_scalar_load_4_reg_904;
wire   [5:0] empty_13_fu_509_p1;
reg   [5:0] empty_13_reg_921;
wire   [4:0] m43_fu_524_p2;
reg   [4:0] m43_reg_929;
wire    ap_CS_fsm_state5;
reg   [3:0] in_scalar_load_6_reg_935;
wire    ap_CS_fsm_state6;
reg   [3:0] in_scalar_load_7_reg_954;
wire    ap_CS_fsm_state7;
wire  signed [3:0] m55_fu_542_p2;
reg   [3:0] m55_reg_960;
wire   [15:0] m27_fu_591_p2;
reg   [15:0] m27_reg_975;
wire    ap_CS_fsm_state15;
wire   [6:0] m114_fu_605_p2;
reg   [6:0] m114_reg_980;
wire   [9:0] m93_fu_640_p2;
reg   [9:0] m93_reg_991;
wire    ap_CS_fsm_state17;
wire   [12:0] m99_fu_650_p2;
reg   [12:0] m99_reg_996;
wire   [4:0] empty_16_fu_657_p1;
reg   [4:0] empty_16_reg_1001;
wire   [4:0] m120_fu_697_p2;
reg   [4:0] m120_reg_1030;
wire    ap_CS_fsm_state25;
reg   [5:0] m64_address0;
reg    m64_ce0;
reg    m64_we0;
wire   [14:0] m64_q0;
wire    grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_start;
wire    grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_idle;
wire    grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_ready;
wire   [3:0] grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_in_data_8_address0;
wire    grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_in_data_8_ce0;
wire   [15:0] grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_m27_1_out;
wire    grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_m27_1_out_ap_vld;
wire   [11:0] grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_phi_ln103_out;
wire    grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_phi_ln103_out_ap_vld;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_start;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_done;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_idle;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_ready;
wire   [3:0] grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_0_address0;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_0_ce0;
wire   [3:0] grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_6_address0;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_6_ce0;
wire   [3:0] grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_10_address0;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_10_ce0;
wire   [3:0] grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_2_address0;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_2_ce0;
wire   [3:0] grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_14_address0;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_14_ce0;
wire   [3:0] grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_8_address0;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_8_ce0;
wire   [3:0] grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_4_address0;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_4_ce0;
wire   [15:0] grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_m27_2_out;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_m27_2_out_ap_vld;
wire   [8:0] grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i5025_phi_out;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i5025_phi_out_ap_vld;
wire   [8:0] grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i4863_phi_out;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i4863_phi_out_ap_vld;
wire  signed [2:0] grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_phi_ln127_out;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_phi_ln127_out_ap_vld;
wire   [8:0] grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_conv3_i_i4798204_phi_out;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_conv3_i_i4798204_phi_out_ap_vld;
wire   [7:0] grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i4277_phi_out;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i4277_phi_out_ap_vld;
wire   [2:0] grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_conv3_i12_i4097189_phi_out;
wire    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_conv3_i12_i4097189_phi_out_ap_vld;
wire    grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_start;
wire    grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_done;
wire    grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_idle;
wire    grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_ready;
wire   [3:0] grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_in_data_12_address0;
wire    grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_in_data_12_ce0;
wire   [15:0] grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_m27_3_out;
wire    grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_m27_3_out_ap_vld;
wire   [8:0] grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_m124_out;
wire    grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_m124_out_ap_vld;
wire    grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_start;
wire    grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_done;
wire    grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_idle;
wire    grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_ready;
wire   [3:0] grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_in_data_0_address0;
wire    grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_in_data_0_ce0;
wire   [15:0] grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_m27_4_out;
wire    grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_m27_4_out_ap_vld;
wire   [2:0] grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_phi_ln146_out;
wire    grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_phi_ln146_out_ap_vld;
wire    grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_start;
wire    grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_done;
wire    grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_idle;
wire    grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_ready;
wire   [3:0] grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_0_address0;
wire    grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_0_ce0;
wire   [3:0] grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_0_address1;
wire    grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_0_ce1;
wire   [5:0] grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_m64_address0;
wire    grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_m64_ce0;
wire    grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_m64_we0;
wire   [14:0] grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_m64_d0;
wire   [3:0] grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_2_address0;
wire    grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_2_ce0;
wire   [3:0] grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_2_address1;
wire    grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_2_ce1;
wire    grp_case_3_Pipeline_L_s1_1_fu_394_ap_start;
wire    grp_case_3_Pipeline_L_s1_1_fu_394_ap_done;
wire    grp_case_3_Pipeline_L_s1_1_fu_394_ap_idle;
wire    grp_case_3_Pipeline_L_s1_1_fu_394_ap_ready;
wire   [3:0] grp_case_3_Pipeline_L_s1_1_fu_394_in_data_2_address0;
wire    grp_case_3_Pipeline_L_s1_1_fu_394_in_data_2_ce0;
wire   [15:0] grp_case_3_Pipeline_L_s1_1_fu_394_m27_7_out;
wire    grp_case_3_Pipeline_L_s1_1_fu_394_m27_7_out_ap_vld;
wire    grp_case_3_Pipeline_L_s2_1_fu_403_ap_start;
wire    grp_case_3_Pipeline_L_s2_1_fu_403_ap_done;
wire    grp_case_3_Pipeline_L_s2_1_fu_403_ap_idle;
wire    grp_case_3_Pipeline_L_s2_1_fu_403_ap_ready;
wire   [3:0] grp_case_3_Pipeline_L_s2_1_fu_403_in_data_8_address0;
wire    grp_case_3_Pipeline_L_s2_1_fu_403_in_data_8_ce0;
wire   [15:0] grp_case_3_Pipeline_L_s2_1_fu_403_m27_10_out;
wire    grp_case_3_Pipeline_L_s2_1_fu_403_m27_10_out_ap_vld;
wire    grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_start;
wire    grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_done;
wire    grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_idle;
wire    grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_ready;
wire   [3:0] grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_4_address0;
wire    grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_4_ce0;
wire   [3:0] grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_14_address0;
wire    grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_14_ce0;
wire   [3:0] grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_6_address0;
wire    grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_6_ce0;
wire   [3:0] grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_2_address0;
wire    grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_2_ce0;
wire   [15:0] grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_m27_13_out;
wire    grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_m27_13_out_ap_vld;
wire   [6:0] grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_mul_i2259_phi_out;
wire    grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_mul_i2259_phi_out_ap_vld;
wire   [7:0] grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_p_phi22_out;
wire    grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_p_phi22_out_ap_vld;
wire    grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_start;
wire    grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_done;
wire    grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_idle;
wire    grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_ready;
wire   [3:0] grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_in_data_2_address0;
wire    grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_in_data_2_ce0;
wire   [15:0] grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_m27_15_out;
wire    grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_m27_15_out_ap_vld;
wire    grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_start;
wire    grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_done;
wire    grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_idle;
wire    grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_ready;
wire   [5:0] grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_m64_address0;
wire    grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_m64_ce0;
wire   [15:0] grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_m27_17_out;
wire    grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_m27_17_out_ap_vld;
wire    grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_start;
wire    grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_done;
wire    grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_idle;
wire    grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_ready;
wire   [3:0] grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_in_data_8_address0;
wire    grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_in_data_8_ce0;
wire   [15:0] grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_m27_19_out;
wire    grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_m27_19_out_ap_vld;
wire    grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_start;
wire    grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_done;
wire    grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_idle;
wire    grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_ready;
wire   [3:0] grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_in_data_0_address0;
wire    grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_in_data_0_ce0;
wire   [3:0] grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_in_data_12_address0;
wire    grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_in_data_12_ce0;
wire   [15:0] grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_m27_21_out;
wire    grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_m27_21_out_ap_vld;
reg    grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_start_reg;
reg    grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_start_reg;
reg    grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_start_reg;
wire    ap_CS_fsm_state8;
reg    grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    grp_case_3_Pipeline_L_s1_1_fu_394_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
reg    grp_case_3_Pipeline_L_s2_1_fu_403_ap_start_reg;
wire    ap_CS_fsm_state16;
reg    grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_start_reg;
wire    ap_CS_fsm_state18;
reg    grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_start_reg;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
reg    grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_start_reg;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
reg    grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_start_reg;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
reg    grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_start_reg;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state27;
reg    in_scalar_ce1_local;
reg   [4:0] in_scalar_address1_local;
reg    in_scalar_ce0_local;
reg   [4:0] in_scalar_address0_local;
wire  signed [3:0] shl_ln_fu_486_p1;
wire  signed [3:0] in_scalar_load_2_cast_fu_495_p0;
wire  signed [4:0] in_scalar_load_5_cast_fu_520_p1;
wire  signed [4:0] in_scalar_load_4_cast_fu_517_p1;
wire   [3:0] empty_fu_538_p1;
wire  signed [4:0] mul_i3155_fu_573_p0;
wire   [4:0] mul_i3155_fu_573_p2;
wire   [13:0] shl_ln1_fu_579_p3;
wire  signed [15:0] sext_ln167_fu_587_p1;
wire   [6:0] empty_14_fu_601_p1;
wire  signed [6:0] conv_i1309_fu_598_p1;
wire  signed [8:0] add_i4863_phi_reload_cast191_fu_636_p0;
wire  signed [9:0] add_i4863_phi_reload_cast191_fu_636_p1;
wire  signed [9:0] phi_ln146_reload_cast_fu_632_p1;
wire  signed [12:0] phi_ln103_reload_cast_fu_614_p1;
wire  signed [12:0] conv_i1963_fu_647_p1;
wire  signed [8:0] empty_16_fu_657_p0;
wire   [4:0] empty_15_fu_693_p1;
reg   [26:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
reg    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 27'd1;
#0 grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_start_reg = 1'b0;
#0 grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_start_reg = 1'b0;
#0 grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_start_reg = 1'b0;
#0 grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_start_reg = 1'b0;
#0 grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_start_reg = 1'b0;
#0 grp_case_3_Pipeline_L_s1_1_fu_394_ap_start_reg = 1'b0;
#0 grp_case_3_Pipeline_L_s2_1_fu_403_ap_start_reg = 1'b0;
#0 grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_start_reg = 1'b0;
#0 grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_start_reg = 1'b0;
#0 grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_start_reg = 1'b0;
#0 grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_start_reg = 1'b0;
#0 grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_start_reg = 1'b0;
end

case_3_m64_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
m64_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(m64_address0),
    .ce0(m64_ce0),
    .we0(m64_we0),
    .d0(grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_m64_d0),
    .q0(m64_q0)
);

case_3_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3 grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_start),
    .ap_done(grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_done),
    .ap_idle(grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_idle),
    .ap_ready(grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_ready),
    .shl_ln94_cast(shl_ln_reg_878),
    .in_data_8_address0(grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_in_data_8_address0),
    .in_data_8_ce0(grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_in_data_8_ce0),
    .in_data_8_q0(in_data_8_q0),
    .sext_ln100(reg_479),
    .m27_1_out(grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_m27_1_out),
    .m27_1_out_ap_vld(grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_m27_1_out_ap_vld),
    .phi_ln103_out(grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_phi_ln103_out),
    .phi_ln103_out_ap_vld(grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_phi_ln103_out_ap_vld)
);

case_3_case_3_Pipeline_L_n3_1_L_n3_2 grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_start),
    .ap_done(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_done),
    .ap_idle(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_idle),
    .ap_ready(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_ready),
    .m27_1_reload(grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_m27_1_out),
    .in_data_0_address0(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_0_address0),
    .in_data_0_ce0(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_0_ce0),
    .in_data_0_q0(in_data_0_q0),
    .in_data_6_address0(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_6_address0),
    .in_data_6_ce0(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_6_ce0),
    .in_data_6_q0(in_data_6_q0),
    .in_data_10_address0(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_10_address0),
    .in_data_10_ce0(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_10_ce0),
    .in_data_10_q0(in_data_10_q0),
    .in_data_2_address0(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_2_address0),
    .in_data_2_ce0(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_2_ce0),
    .in_data_2_q0(in_data_2_q0),
    .in_data_14_address0(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_14_address0),
    .in_data_14_ce0(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_14_ce0),
    .in_data_14_q0(in_data_14_q0),
    .in_scalar_load_2_cast(reg_479),
    .in_data_8_address0(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_8_address0),
    .in_data_8_ce0(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_8_ce0),
    .in_data_8_q0(in_data_8_q0),
    .in_data_4_address0(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_4_address0),
    .in_data_4_ce0(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_4_ce0),
    .in_data_4_q0(in_data_4_q0),
    .m43_cast70(m43_reg_929),
    .mul_i4971_cast(m38_reg_898),
    .sext_ln108_1(in_scalar_load_6_reg_935),
    .m27_2_out(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_m27_2_out),
    .m27_2_out_ap_vld(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_m27_2_out_ap_vld),
    .add_i5025_phi_out(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i5025_phi_out),
    .add_i5025_phi_out_ap_vld(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i5025_phi_out_ap_vld),
    .add_i4863_phi_out(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i4863_phi_out),
    .add_i4863_phi_out_ap_vld(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i4863_phi_out_ap_vld),
    .phi_ln127_out(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_phi_ln127_out),
    .phi_ln127_out_ap_vld(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_phi_ln127_out_ap_vld),
    .conv3_i_i4798204_phi_out(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_conv3_i_i4798204_phi_out),
    .conv3_i_i4798204_phi_out_ap_vld(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_conv3_i_i4798204_phi_out_ap_vld),
    .add_i4277_phi_out(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i4277_phi_out),
    .add_i4277_phi_out_ap_vld(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i4277_phi_out_ap_vld),
    .conv3_i12_i4097189_phi_out(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_conv3_i12_i4097189_phi_out),
    .conv3_i12_i4097189_phi_out_ap_vld(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_conv3_i12_i4097189_phi_out_ap_vld)
);

case_3_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3 grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_start),
    .ap_done(grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_done),
    .ap_idle(grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_idle),
    .ap_ready(grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_ready),
    .m27_2_reload(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_m27_2_out),
    .in_data_12_address0(grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_in_data_12_address0),
    .in_data_12_ce0(grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_in_data_12_ce0),
    .in_data_12_q0(in_data_12_q0),
    .conv_i3873_cast(m43_reg_929),
    .sext_ln131(in_scalar_load_7_reg_954),
    .sext_ln22(m55_reg_960),
    .m27_3_out(grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_m27_3_out),
    .m27_3_out_ap_vld(grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_m27_3_out_ap_vld),
    .m124_out(grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_m124_out),
    .m124_out_ap_vld(grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_m124_out_ap_vld)
);

case_3_case_3_Pipeline_L_n5_1_L_n5_2 grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_start),
    .ap_done(grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_done),
    .ap_idle(grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_idle),
    .ap_ready(grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_ready),
    .m27_3_reload(grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_m27_3_out),
    .in_data_0_address0(grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_in_data_0_address0),
    .in_data_0_ce0(grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_in_data_0_ce0),
    .in_data_0_q0(in_data_0_q0),
    .m27_4_out(grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_m27_4_out),
    .m27_4_out_ap_vld(grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_m27_4_out_ap_vld),
    .phi_ln146_out(grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_phi_ln146_out),
    .phi_ln146_out_ap_vld(grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_phi_ln146_out_ap_vld)
);

case_3_case_3_Pipeline_L_m1_1_L_m1_2 grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_start),
    .ap_done(grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_done),
    .ap_idle(grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_idle),
    .ap_ready(grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_ready),
    .in_data_0_address0(grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_0_address0),
    .in_data_0_ce0(grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_0_ce0),
    .in_data_0_q0(in_data_0_q0),
    .in_data_0_address1(grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_0_address1),
    .in_data_0_ce1(grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_0_ce1),
    .in_data_0_q1(in_data_0_q1),
    .m64_address0(grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_m64_address0),
    .m64_ce0(grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_m64_ce0),
    .m64_we0(grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_m64_we0),
    .m64_d0(grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_m64_d0),
    .in_data_2_address0(grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_2_address0),
    .in_data_2_ce0(grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_2_ce0),
    .in_data_2_q0(in_data_2_q0),
    .in_data_2_address1(grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_2_address1),
    .in_data_2_ce1(grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_2_ce1),
    .in_data_2_q1(in_data_2_q1)
);

case_3_case_3_Pipeline_L_s1_1 grp_case_3_Pipeline_L_s1_1_fu_394(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_case_3_Pipeline_L_s1_1_fu_394_ap_start),
    .ap_done(grp_case_3_Pipeline_L_s1_1_fu_394_ap_done),
    .ap_idle(grp_case_3_Pipeline_L_s1_1_fu_394_ap_idle),
    .ap_ready(grp_case_3_Pipeline_L_s1_1_fu_394_ap_ready),
    .m27_4_reload(grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_m27_4_out),
    .in_data_2_address0(grp_case_3_Pipeline_L_s1_1_fu_394_in_data_2_address0),
    .in_data_2_ce0(grp_case_3_Pipeline_L_s1_1_fu_394_in_data_2_ce0),
    .in_data_2_q0(in_data_2_q0),
    .sext_ln22_1(in_scalar_load_reg_872),
    .m27_7_out(grp_case_3_Pipeline_L_s1_1_fu_394_m27_7_out),
    .m27_7_out_ap_vld(grp_case_3_Pipeline_L_s1_1_fu_394_m27_7_out_ap_vld)
);

case_3_case_3_Pipeline_L_s2_1 grp_case_3_Pipeline_L_s2_1_fu_403(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_case_3_Pipeline_L_s2_1_fu_403_ap_start),
    .ap_done(grp_case_3_Pipeline_L_s2_1_fu_403_ap_done),
    .ap_idle(grp_case_3_Pipeline_L_s2_1_fu_403_ap_idle),
    .ap_ready(grp_case_3_Pipeline_L_s2_1_fu_403_ap_ready),
    .m27_6(m27_reg_975),
    .in_data_8_address0(grp_case_3_Pipeline_L_s2_1_fu_403_in_data_8_address0),
    .in_data_8_ce0(grp_case_3_Pipeline_L_s2_1_fu_403_in_data_8_ce0),
    .in_data_8_q0(in_data_8_q0),
    .sext_ln184(in_scalar_load_6_reg_935),
    .m27_10_out(grp_case_3_Pipeline_L_s2_1_fu_403_m27_10_out),
    .m27_10_out_ap_vld(grp_case_3_Pipeline_L_s2_1_fu_403_m27_10_out_ap_vld)
);

case_3_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3 grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_start),
    .ap_done(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_done),
    .ap_idle(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_idle),
    .ap_ready(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_ready),
    .m27_10_reload(grp_case_3_Pipeline_L_s2_1_fu_403_m27_10_out),
    .in_data_4_address0(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_4_address0),
    .in_data_4_ce0(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_4_ce0),
    .in_data_4_q0(in_data_4_q0),
    .in_data_14_address0(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_14_address0),
    .in_data_14_ce0(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_14_ce0),
    .in_data_14_q0(in_data_14_q0),
    .in_data_6_address0(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_6_address0),
    .in_data_6_ce0(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_6_ce0),
    .in_data_6_q0(in_data_6_q0),
    .in_data_2_address0(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_2_address0),
    .in_data_2_ce0(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_2_ce0),
    .in_data_2_q0(in_data_2_q0),
    .in_scalar_load_2_cast31(reg_479),
    .sext_ln205(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i5025_phi_out),
    .empty(empty_13_reg_921),
    .sext_ln22_2(in_scalar_load_7_reg_954),
    .conv3_i_i4798204_phi_reload(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_conv3_i_i4798204_phi_out),
    .conv3_i12_i180886(m99_reg_996),
    .m93_cast(m93_reg_991),
    .m27_13_out(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_m27_13_out),
    .m27_13_out_ap_vld(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_m27_13_out_ap_vld),
    .mul_i2259_phi_out(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_mul_i2259_phi_out),
    .mul_i2259_phi_out_ap_vld(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_mul_i2259_phi_out_ap_vld),
    .p_phi22_out(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_p_phi22_out),
    .p_phi22_out_ap_vld(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_p_phi22_out_ap_vld)
);

case_3_case_3_Pipeline_L_n9_1_L_n9_2 grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_start),
    .ap_done(grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_done),
    .ap_idle(grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_idle),
    .ap_ready(grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_ready),
    .m27_13_reload(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_m27_13_out),
    .in_data_2_address0(grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_in_data_2_address0),
    .in_data_2_ce0(grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_in_data_2_ce0),
    .in_data_2_q0(in_data_2_q0),
    .sext_ln220(in_scalar_load_4_reg_904),
    .m27_15_out(grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_m27_15_out),
    .m27_15_out_ap_vld(grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_m27_15_out_ap_vld)
);

case_3_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3 grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_start),
    .ap_done(grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_done),
    .ap_idle(grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_idle),
    .ap_ready(grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_ready),
    .m27_15_reload(grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_m27_15_out),
    .m64_address0(grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_m64_address0),
    .m64_ce0(grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_m64_ce0),
    .m64_q0(m64_q0),
    .sext_ln228(m38_reg_898),
    .conv3_i12_i132751(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i4277_phi_out),
    .m27_17_out(grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_m27_17_out),
    .m27_17_out_ap_vld(grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_m27_17_out_ap_vld)
);

case_3_case_3_Pipeline_L_n11_1_L_n11_2 grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_start),
    .ap_done(grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_done),
    .ap_idle(grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_idle),
    .ap_ready(grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_ready),
    .m27_17_reload(grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_m27_17_out),
    .in_data_8_address0(grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_in_data_8_address0),
    .in_data_8_ce0(grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_in_data_8_ce0),
    .in_data_8_q0(in_data_8_q0),
    .in_scalar_load_6_cast34(in_scalar_load_6_reg_935),
    .sext_ln22_3(m114_reg_980),
    .m27_19_out(grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_m27_19_out),
    .m27_19_out_ap_vld(grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_m27_19_out_ap_vld)
);

case_3_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3 grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_start),
    .ap_done(grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_done),
    .ap_idle(grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_idle),
    .ap_ready(grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_ready),
    .m27_19_reload(grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_m27_19_out),
    .in_data_0_address0(grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_in_data_0_address0),
    .in_data_0_ce0(grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_in_data_0_ce0),
    .in_data_0_q0(in_data_0_q0),
    .sext_ln247(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_mul_i2259_phi_out),
    .in_data_12_address0(grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_in_data_12_address0),
    .in_data_12_ce0(grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_in_data_12_ce0),
    .in_data_12_q0(in_data_12_q0),
    .sext_ln22_4(grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_p_phi22_out),
    .sext_ln241(grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_m124_out),
    .conv3_i12_i4097189_phi_reload(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_conv3_i12_i4097189_phi_out),
    .m120_cast(m120_reg_1030),
    .sext_ln108(in_scalar_load_6_reg_935),
    .m27_21_out(grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_m27_21_out),
    .m27_21_out_ap_vld(grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_m27_21_out_ap_vld)
);

case_3_mul_4s_4s_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
mul_4s_4s_8_1_1_U116(
    .din0(in_scalar_q0),
    .din1(in_scalar_load_2_cast_fu_495_p0),
    .dout(m38_fu_503_p2)
);

case_3_mul_5s_3s_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 5 ))
mul_5s_3s_5_1_1_U117(
    .din0(mul_i3155_fu_573_p0),
    .din1(grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_phi_ln127_out),
    .dout(mul_i3155_fu_573_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_start_reg <= 1'b1;
        end else if ((grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_ready == 1'b1)) begin
            grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_start_reg <= 1'b1;
        end else if ((grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_ready == 1'b1)) begin
            grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state23)) begin
            grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_start_reg <= 1'b1;
        end else if ((grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_ready == 1'b1)) begin
            grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state25)) begin
            grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_start_reg <= 1'b1;
        end else if ((grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_ready == 1'b1)) begin
            grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_start_reg <= 1'b1;
        end else if ((grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_ready == 1'b1)) begin
            grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_start_reg <= 1'b1;
        end else if ((grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_ready == 1'b1)) begin
            grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_start_reg <= 1'b1;
        end else if ((grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_ready == 1'b1)) begin
            grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_start_reg <= 1'b1;
        end else if ((grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_ready == 1'b1)) begin
            grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_start_reg <= 1'b1;
        end else if ((grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_ready == 1'b1)) begin
            grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state19)) begin
            grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_start_reg <= 1'b1;
        end else if ((grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_ready == 1'b1)) begin
            grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_case_3_Pipeline_L_s1_1_fu_394_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_case_3_Pipeline_L_s1_1_fu_394_ap_start_reg <= 1'b1;
        end else if ((grp_case_3_Pipeline_L_s1_1_fu_394_ap_ready == 1'b1)) begin
            grp_case_3_Pipeline_L_s1_1_fu_394_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_case_3_Pipeline_L_s2_1_fu_403_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            grp_case_3_Pipeline_L_s2_1_fu_403_ap_start_reg <= 1'b1;
        end else if ((grp_case_3_Pipeline_L_s2_1_fu_403_ap_ready == 1'b1)) begin
            grp_case_3_Pipeline_L_s2_1_fu_403_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        empty_13_reg_921 <= empty_13_fu_509_p1;
        in_scalar_load_4_reg_904 <= in_scalar_q1;
        m38_reg_898 <= m38_fu_503_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        empty_16_reg_1001 <= empty_16_fu_657_p1;
        m93_reg_991 <= m93_fu_640_p2;
        m99_reg_996 <= m99_fu_650_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_scalar_load_6_reg_935 <= in_scalar_q1;
        m43_reg_929 <= m43_fu_524_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        in_scalar_load_7_reg_954 <= in_scalar_q1;
        m55_reg_960 <= m55_fu_542_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        in_scalar_load_reg_872 <= in_scalar_q1;
        shl_ln_reg_878[9 : 6] <= shl_ln_fu_486_p3[9 : 6];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        m114_reg_980 <= m114_fu_605_p2;
        m27_reg_975 <= m27_fu_591_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        m120_reg_1030 <= m120_fu_697_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        reg_479 <= in_scalar_q0;
    end
end

always @ (*) begin
    if ((grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_case_3_Pipeline_L_s1_1_fu_394_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((grp_case_3_Pipeline_L_s2_1_fu_403_ap_done == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_done == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

always @ (*) begin
    if ((grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_done == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

assign ap_ST_fsm_state23_blk = 1'b0;

always @ (*) begin
    if ((grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_done == 1'b0)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

assign ap_ST_fsm_state25_blk = 1'b0;

always @ (*) begin
    if ((grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_done == 1'b0)) begin
        ap_ST_fsm_state26_blk = 1'b1;
    end else begin
        ap_ST_fsm_state26_blk = 1'b0;
    end
end

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        in_data_0_address0 = grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_in_data_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        in_data_0_address0 = grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        in_data_0_address0 = grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_in_data_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_data_0_address0 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_0_address0;
    end else begin
        in_data_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        in_data_0_ce0 = grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_in_data_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        in_data_0_ce0 = grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        in_data_0_ce0 = grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_in_data_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_data_0_ce0 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_0_ce0;
    end else begin
        in_data_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        in_data_0_ce1 = grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_0_ce1;
    end else begin
        in_data_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        in_data_12_address0 = grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_in_data_12_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        in_data_12_address0 = grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_in_data_12_address0;
    end else begin
        in_data_12_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        in_data_12_ce0 = grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_in_data_12_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        in_data_12_ce0 = grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_in_data_12_ce0;
    end else begin
        in_data_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        in_data_14_address0 = grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_14_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_data_14_address0 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_14_address0;
    end else begin
        in_data_14_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        in_data_14_ce0 = grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_14_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_data_14_ce0 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_14_ce0;
    end else begin
        in_data_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        in_data_2_address0 = grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_in_data_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        in_data_2_address0 = grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        in_data_2_address0 = grp_case_3_Pipeline_L_s1_1_fu_394_in_data_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        in_data_2_address0 = grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_data_2_address0 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_2_address0;
    end else begin
        in_data_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        in_data_2_ce0 = grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_in_data_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        in_data_2_ce0 = grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        in_data_2_ce0 = grp_case_3_Pipeline_L_s1_1_fu_394_in_data_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        in_data_2_ce0 = grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_data_2_ce0 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_2_ce0;
    end else begin
        in_data_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        in_data_2_ce1 = grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_2_ce1;
    end else begin
        in_data_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        in_data_4_address0 = grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_data_4_address0 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_4_address0;
    end else begin
        in_data_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        in_data_4_ce0 = grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_data_4_ce0 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_4_ce0;
    end else begin
        in_data_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        in_data_6_address0 = grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_data_6_address0 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_6_address0;
    end else begin
        in_data_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        in_data_6_ce0 = grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_in_data_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_data_6_ce0 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_6_ce0;
    end else begin
        in_data_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        in_data_8_address0 = grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_in_data_8_address0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        in_data_8_address0 = grp_case_3_Pipeline_L_s2_1_fu_403_in_data_8_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_data_8_address0 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_8_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_data_8_address0 = grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_in_data_8_address0;
    end else begin
        in_data_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        in_data_8_ce0 = grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_in_data_8_ce0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        in_data_8_ce0 = grp_case_3_Pipeline_L_s2_1_fu_403_in_data_8_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_data_8_ce0 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_8_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_data_8_ce0 = grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_in_data_8_ce0;
    end else begin
        in_data_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        in_scalar_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_scalar_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_scalar_address0_local = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        in_scalar_address0_local = 64'd1;
    end else begin
        in_scalar_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        in_scalar_address1_local = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        in_scalar_address1_local = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_scalar_address1_local = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        in_scalar_address1_local = 64'd11;
    end else begin
        in_scalar_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        in_scalar_ce0_local = 1'b1;
    end else begin
        in_scalar_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        in_scalar_ce1_local = 1'b1;
    end else begin
        in_scalar_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        m64_address0 = grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_m64_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        m64_address0 = grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_m64_address0;
    end else begin
        m64_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        m64_ce0 = grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_m64_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        m64_ce0 = grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_m64_ce0;
    end else begin
        m64_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        m64_we0 = grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_m64_we0;
    end else begin
        m64_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_case_3_Pipeline_L_s1_1_fu_394_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((grp_case_3_Pipeline_L_s2_1_fu_403_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            if (((grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_i4863_phi_reload_cast191_fu_636_p0 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i4863_phi_out;

assign add_i4863_phi_reload_cast191_fu_636_p1 = add_i4863_phi_reload_cast191_fu_636_p0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign conv_i1309_fu_598_p1 = $signed(m55_reg_960);

assign conv_i1963_fu_647_p1 = $signed(in_scalar_load_reg_872);

assign empty_13_fu_509_p1 = m38_fu_503_p2[5:0];

assign empty_14_fu_601_p1 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i5025_phi_out[6:0];

assign empty_15_fu_693_p1 = grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_mul_i2259_phi_out[4:0];

assign empty_16_fu_657_p0 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i4863_phi_out;

assign empty_16_fu_657_p1 = empty_16_fu_657_p0[4:0];

assign empty_fu_538_p1 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i4277_phi_out[3:0];

assign grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_start = grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_ap_start_reg;

assign grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_start = grp_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3_fu_444_ap_start_reg;

assign grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_start = grp_case_3_Pipeline_L_n11_1_L_n11_2_fu_453_ap_start_reg;

assign grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_start = grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_ap_start_reg;

assign grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_start = grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_ap_start_reg;

assign grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_start = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_ap_start_reg;

assign grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_start = grp_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3_fu_363_ap_start_reg;

assign grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_start = grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_ap_start_reg;

assign grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_start = grp_case_3_Pipeline_L_n8_1_L_n8_2_L_n8_3_fu_412_ap_start_reg;

assign grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_start = grp_case_3_Pipeline_L_n9_1_L_n9_2_fu_435_ap_start_reg;

assign grp_case_3_Pipeline_L_s1_1_fu_394_ap_start = grp_case_3_Pipeline_L_s1_1_fu_394_ap_start_reg;

assign grp_case_3_Pipeline_L_s2_1_fu_403_ap_start = grp_case_3_Pipeline_L_s2_1_fu_403_ap_start_reg;

assign in_data_0_address1 = grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_0_address1;

assign in_data_10_address0 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_10_address0;

assign in_data_10_ce0 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_in_data_10_ce0;

assign in_data_11_address0 = 4'd0;

assign in_data_11_address1 = 4'd0;

assign in_data_11_ce0 = 1'b0;

assign in_data_11_ce1 = 1'b0;

assign in_data_11_d0 = 8'd0;

assign in_data_11_d1 = 8'd0;

assign in_data_11_we0 = 1'b0;

assign in_data_11_we1 = 1'b0;

assign in_data_13_address0 = 4'd0;

assign in_data_13_address1 = 4'd0;

assign in_data_13_ce0 = 1'b0;

assign in_data_13_ce1 = 1'b0;

assign in_data_13_d0 = 8'd0;

assign in_data_13_d1 = 8'd0;

assign in_data_13_we0 = 1'b0;

assign in_data_13_we1 = 1'b0;

assign in_data_15_address0 = 4'd0;

assign in_data_15_address1 = 4'd0;

assign in_data_15_ce0 = 1'b0;

assign in_data_15_ce1 = 1'b0;

assign in_data_15_d0 = 8'd0;

assign in_data_15_d1 = 8'd0;

assign in_data_15_we0 = 1'b0;

assign in_data_15_we1 = 1'b0;

assign in_data_1_address0 = 4'd0;

assign in_data_1_address1 = 4'd0;

assign in_data_1_ce0 = 1'b0;

assign in_data_1_ce1 = 1'b0;

assign in_data_1_d0 = 8'd0;

assign in_data_1_d1 = 8'd0;

assign in_data_1_we0 = 1'b0;

assign in_data_1_we1 = 1'b0;

assign in_data_2_address1 = grp_case_3_Pipeline_L_m1_1_L_m1_2_fu_385_in_data_2_address1;

assign in_data_3_address0 = 4'd0;

assign in_data_3_address1 = 4'd0;

assign in_data_3_ce0 = 1'b0;

assign in_data_3_ce1 = 1'b0;

assign in_data_3_d0 = 8'd0;

assign in_data_3_d1 = 8'd0;

assign in_data_3_we0 = 1'b0;

assign in_data_3_we1 = 1'b0;

assign in_data_5_address0 = 4'd0;

assign in_data_5_address1 = 4'd0;

assign in_data_5_ce0 = 1'b0;

assign in_data_5_ce1 = 1'b0;

assign in_data_5_d0 = 8'd0;

assign in_data_5_d1 = 8'd0;

assign in_data_5_we0 = 1'b0;

assign in_data_5_we1 = 1'b0;

assign in_data_7_address0 = 4'd0;

assign in_data_7_address1 = 4'd0;

assign in_data_7_ce0 = 1'b0;

assign in_data_7_ce1 = 1'b0;

assign in_data_7_d0 = 8'd0;

assign in_data_7_d1 = 8'd0;

assign in_data_7_we0 = 1'b0;

assign in_data_7_we1 = 1'b0;

assign in_data_9_address0 = 4'd0;

assign in_data_9_address1 = 4'd0;

assign in_data_9_ce0 = 1'b0;

assign in_data_9_ce1 = 1'b0;

assign in_data_9_d0 = 8'd0;

assign in_data_9_d1 = 8'd0;

assign in_data_9_we0 = 1'b0;

assign in_data_9_we1 = 1'b0;

assign in_scalar_address0 = in_scalar_address0_local;

assign in_scalar_address1 = in_scalar_address1_local;

assign in_scalar_ce0 = in_scalar_ce0_local;

assign in_scalar_ce1 = in_scalar_ce1_local;

assign in_scalar_load_2_cast_fu_495_p0 = reg_479;

assign in_scalar_load_4_cast_fu_517_p1 = $signed(in_scalar_load_4_reg_904);

assign in_scalar_load_5_cast_fu_520_p1 = $signed(in_scalar_q0);

assign m114_fu_605_p2 = ($signed(empty_14_fu_601_p1) + $signed(conv_i1309_fu_598_p1));

assign m120_fu_697_p2 = (empty_15_fu_693_p1 + empty_16_reg_1001);

assign m27_fu_591_p2 = ($signed(grp_case_3_Pipeline_L_s1_1_fu_394_m27_7_out) + $signed(sext_ln167_fu_587_p1));

assign m43_fu_524_p2 = ($signed(in_scalar_load_5_cast_fu_520_p1) + $signed(in_scalar_load_4_cast_fu_517_p1));

assign m55_fu_542_p2 = (in_scalar_load_4_reg_904 + empty_fu_538_p1);

assign m93_fu_640_p2 = ($signed(add_i4863_phi_reload_cast191_fu_636_p1) + $signed(phi_ln146_reload_cast_fu_632_p1));

assign m99_fu_650_p2 = ($signed(phi_ln103_reload_cast_fu_614_p1) + $signed(conv_i1963_fu_647_p1));

assign mul_i3155_fu_573_p0 = grp_case_3_Pipeline_L_n3_1_L_n3_2_fu_332_add_i5025_phi_out[4:0];

assign out_data_0 = grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_m27_21_out[7:0];

assign out_data_1 = {{grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_m27_21_out[15:8]}};

assign out_data_2 = {{grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_m27_21_out[22:15]}};

assign out_data_3 = {{grp_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3_fu_463_m27_21_out[22:15]}};

assign phi_ln103_reload_cast_fu_614_p1 = $signed(grp_case_3_Pipeline_L_n2_1_L_n2_2_L_n2_3_fu_321_phi_ln103_out);

assign phi_ln146_reload_cast_fu_632_p1 = $signed(grp_case_3_Pipeline_L_n5_1_L_n5_2_fu_376_phi_ln146_out);

assign sext_ln167_fu_587_p1 = $signed(shl_ln1_fu_579_p3);

assign shl_ln1_fu_579_p3 = {{mul_i3155_fu_573_p2}, {9'd0}};

assign shl_ln_fu_486_p1 = in_scalar_q1;

assign shl_ln_fu_486_p3 = {{shl_ln_fu_486_p1}, {6'd0}};

always @ (posedge ap_clk) begin
    shl_ln_reg_878[5:0] <= 6'b000000;
end

endmodule //case_3
