// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module case_3_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m27_2_reload,
        in_data_12_address0,
        in_data_12_ce0,
        in_data_12_q0,
        conv_i3873_cast,
        sext_ln131,
        sext_ln22,
        m27_3_out,
        m27_3_out_ap_vld,
        m124_out,
        m124_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] m27_2_reload;
output  [3:0] in_data_12_address0;
output   in_data_12_ce0;
input  [7:0] in_data_12_q0;
input  [4:0] conv_i3873_cast;
input  [3:0] sext_ln131;
input  [3:0] sext_ln22;
output  [15:0] m27_3_out;
output   m27_3_out_ap_vld;
output  [8:0] m124_out;
output   m124_out_ap_vld;

reg ap_idle;
reg m27_3_out_ap_vld;
reg m124_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln131_fu_174_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [4:0] sext_ln22_cast_fu_139_p1;
reg  signed [4:0] sext_ln22_cast_reg_358;
wire  signed [4:0] sext_ln131_cast_fu_143_p1;
reg  signed [4:0] sext_ln131_cast_reg_363;
wire  signed [8:0] conv_i3873_cast_cast_fu_147_p1;
reg  signed [8:0] conv_i3873_cast_cast_reg_368;
reg   [0:0] icmp_ln131_reg_373;
wire   [8:0] m56_fu_274_p2;
reg   [8:0] m56_reg_382;
wire   [63:0] zext_ln133_fu_230_p1;
wire    ap_block_pp0_stage0;
reg   [8:0] m124_fu_68;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [15:0] m27_3_fu_72;
wire   [15:0] m27_fu_304_p2;
wire    ap_loop_init;
reg   [3:0] i_n4_2_fu_76;
wire   [3:0] add_ln133_fu_235_p2;
reg   [3:0] ap_sig_allocacmp_i_n4_2_load;
reg   [7:0] indvar_flatten28_fu_80;
wire   [7:0] select_ln132_fu_247_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten28_load;
reg   [9:0] indvar_flatten43_fu_84;
wire   [9:0] add_ln131_fu_180_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten43_load;
wire    ap_block_pp0_stage0_01001;
reg    in_data_12_ce0_local;
wire   [0:0] icmp_ln132_fu_192_p2;
wire   [0:0] icmp_ln133_fu_204_p2;
wire   [0:0] xor_ln22_fu_198_p2;
wire   [0:0] and_ln22_fu_210_p2;
wire   [0:0] or_ln22_fu_216_p2;
wire   [3:0] select_ln22_fu_222_p3;
wire   [7:0] add_ln132_fu_241_p2;
wire  signed [8:0] sext_ln138_fu_270_p1;
wire   [4:0] add_ln139_fu_287_p2;
wire  signed [8:0] sext_ln139_fu_291_p1;
wire   [8:0] add_ln139_1_fu_295_p2;
wire  signed [15:0] sext_ln139_1_fu_300_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 m124_fu_68 = 9'd0;
#0 m27_3_fu_72 = 16'd0;
#0 i_n4_2_fu_76 = 4'd0;
#0 indvar_flatten28_fu_80 = 8'd0;
#0 indvar_flatten43_fu_84 = 10'd0;
#0 ap_done_reg = 1'b0;
end

case_3_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln131_fu_174_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_n4_2_fu_76 <= add_ln133_fu_235_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_n4_2_fu_76 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln131_fu_174_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten28_fu_80 <= select_ln132_fu_247_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten28_fu_80 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln131_fu_174_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten43_fu_84 <= add_ln131_fu_180_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten43_fu_84 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            m27_3_fu_72 <= m27_2_reload;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            m27_3_fu_72 <= m27_fu_304_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        conv_i3873_cast_cast_reg_368 <= conv_i3873_cast_cast_fu_147_p1;
        icmp_ln131_reg_373 <= icmp_ln131_fu_174_p2;
        m56_reg_382 <= m56_fu_274_p2;
        sext_ln131_cast_reg_363 <= sext_ln131_cast_fu_143_p1;
        sext_ln22_cast_reg_358 <= sext_ln22_cast_fu_139_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m124_fu_68 <= m56_fu_274_p2;
    end
end

always @ (*) begin
    if (((icmp_ln131_fu_174_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_n4_2_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i_n4_2_load = i_n4_2_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten28_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten28_load = indvar_flatten28_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten43_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten43_load = indvar_flatten43_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_data_12_ce0_local = 1'b1;
    end else begin
        in_data_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln131_reg_373 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        m124_out_ap_vld = 1'b1;
    end else begin
        m124_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln131_reg_373 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        m27_3_out_ap_vld = 1'b1;
    end else begin
        m27_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln131_fu_180_p2 = (ap_sig_allocacmp_indvar_flatten43_load + 10'd1);

assign add_ln132_fu_241_p2 = (ap_sig_allocacmp_indvar_flatten28_load + 8'd1);

assign add_ln133_fu_235_p2 = (select_ln22_fu_222_p3 + 4'd1);

assign add_ln139_1_fu_295_p2 = ($signed(sext_ln139_fu_291_p1) + $signed(m56_reg_382));

assign add_ln139_fu_287_p2 = ($signed(sext_ln131_cast_reg_363) + $signed(sext_ln22_cast_reg_358));

assign and_ln22_fu_210_p2 = (xor_ln22_fu_198_p2 & icmp_ln133_fu_204_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign conv_i3873_cast_cast_fu_147_p1 = $signed(conv_i3873_cast);

assign icmp_ln131_fu_174_p2 = ((ap_sig_allocacmp_indvar_flatten43_load == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln132_fu_192_p2 = ((ap_sig_allocacmp_indvar_flatten28_load == 8'd64) ? 1'b1 : 1'b0);

assign icmp_ln133_fu_204_p2 = ((ap_sig_allocacmp_i_n4_2_load == 4'd8) ? 1'b1 : 1'b0);

assign in_data_12_address0 = zext_ln133_fu_230_p1;

assign in_data_12_ce0 = in_data_12_ce0_local;

assign m124_out = m124_fu_68;

assign m27_3_out = m27_3_fu_72;

assign m27_fu_304_p2 = ($signed(m27_3_fu_72) + $signed(sext_ln139_1_fu_300_p1));

assign m56_fu_274_p2 = ($signed(sext_ln138_fu_270_p1) + $signed(conv_i3873_cast_cast_reg_368));

assign or_ln22_fu_216_p2 = (icmp_ln132_fu_192_p2 | and_ln22_fu_210_p2);

assign select_ln132_fu_247_p3 = ((icmp_ln132_fu_192_p2[0:0] == 1'b1) ? 8'd1 : add_ln132_fu_241_p2);

assign select_ln22_fu_222_p3 = ((or_ln22_fu_216_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_i_n4_2_load);

assign sext_ln131_cast_fu_143_p1 = $signed(sext_ln131);

assign sext_ln138_fu_270_p1 = $signed(in_data_12_q0);

assign sext_ln139_1_fu_300_p1 = $signed(add_ln139_1_fu_295_p2);

assign sext_ln139_fu_291_p1 = $signed(add_ln139_fu_287_p2);

assign sext_ln22_cast_fu_139_p1 = $signed(sext_ln22);

assign xor_ln22_fu_198_p2 = (icmp_ln132_fu_192_p2 ^ 1'd1);

assign zext_ln133_fu_230_p1 = select_ln22_fu_222_p3;

endmodule //case_3_case_3_Pipeline_L_n4_1_L_n4_2_L_n4_3
