// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module case_3_case_3_Pipeline_L_s1_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m27_4_reload,
        in_data_2_address0,
        in_data_2_ce0,
        in_data_2_q0,
        sext_ln22_1,
        m27_7_out,
        m27_7_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] m27_4_reload;
output  [3:0] in_data_2_address0;
output   in_data_2_ce0;
input  [7:0] in_data_2_q0;
input  [3:0] sext_ln22_1;
output  [15:0] m27_7_out;
output   m27_7_out_ap_vld;

reg ap_idle;
reg m27_7_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln163_fu_103_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire  signed [4:0] sext_ln22_1_cast_fu_86_p1;
reg  signed [4:0] sext_ln22_1_cast_reg_181;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln163_fu_115_p1;
wire    ap_block_pp0_stage0;
reg   [15:0] m27_fu_46;
wire   [15:0] m27_2_fu_151_p2;
wire    ap_loop_init;
reg   [3:0] i_s1_0_fu_50;
wire   [3:0] add_ln163_fu_109_p2;
reg   [3:0] ap_sig_allocacmp_i_s1_0_1;
wire    ap_block_pp0_stage0_01001;
reg    in_data_2_ce0_local;
wire   [4:0] add_ln165_1_fu_132_p2;
wire  signed [8:0] sext_ln165_2_fu_137_p1;
wire  signed [8:0] sext_ln165_1_fu_128_p1;
wire   [8:0] add_ln165_fu_141_p2;
wire  signed [15:0] sext_ln165_fu_147_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 m27_fu_46 = 16'd0;
#0 i_s1_0_fu_50 = 4'd0;
#0 ap_done_reg = 1'b0;
end

case_3_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln163_fu_103_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_s1_0_fu_50 <= add_ln163_fu_109_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_s1_0_fu_50 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m27_fu_46 <= m27_4_reload;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            m27_fu_46 <= m27_2_fu_151_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sext_ln22_1_cast_reg_181 <= sext_ln22_1_cast_fu_86_p1;
    end
end

always @ (*) begin
    if (((icmp_ln163_fu_103_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_s1_0_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_s1_0_1 = i_s1_0_fu_50;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_data_2_ce0_local = 1'b1;
    end else begin
        in_data_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln163_fu_103_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m27_7_out_ap_vld = 1'b1;
    end else begin
        m27_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln163_fu_109_p2 = (ap_sig_allocacmp_i_s1_0_1 + 4'd1);

assign add_ln165_1_fu_132_p2 = ($signed(sext_ln22_1_cast_reg_181) + $signed(5'd1));

assign add_ln165_fu_141_p2 = ($signed(sext_ln165_2_fu_137_p1) + $signed(sext_ln165_1_fu_128_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln163_fu_103_p2 = ((ap_sig_allocacmp_i_s1_0_1 == 4'd8) ? 1'b1 : 1'b0);

assign in_data_2_address0 = zext_ln163_fu_115_p1;

assign in_data_2_ce0 = in_data_2_ce0_local;

assign m27_2_fu_151_p2 = ($signed(sext_ln165_fu_147_p1) + $signed(m27_fu_46));

assign m27_7_out = m27_fu_46;

assign sext_ln165_1_fu_128_p1 = $signed(in_data_2_q0);

assign sext_ln165_2_fu_137_p1 = $signed(add_ln165_1_fu_132_p2);

assign sext_ln165_fu_147_p1 = $signed(add_ln165_fu_141_p2);

assign sext_ln22_1_cast_fu_86_p1 = $signed(sext_ln22_1);

assign zext_ln163_fu_115_p1 = ap_sig_allocacmp_i_s1_0_1;

endmodule //case_3_case_3_Pipeline_L_s1_1
