-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity case_9_case_9_Pipeline_L_s4_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m16_17 : IN STD_LOGIC_VECTOR (31 downto 0);
    in_data_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in_data_4_ce0 : OUT STD_LOGIC;
    in_data_4_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    mul_i1148_phi : IN STD_LOGIC_VECTOR (6 downto 0);
    in_data_14_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in_data_14_ce0 : OUT STD_LOGIC;
    in_data_14_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    phi_ln130 : IN STD_LOGIC_VECTOR (9 downto 0);
    sext_ln22_3 : IN STD_LOGIC_VECTOR (4 downto 0);
    m16_19_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m16_19_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of case_9_case_9_Pipeline_L_s4_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln265_fu_148_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln22_3_cast_fu_131_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln22_3_cast_reg_257 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln265_reg_262 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_data_14_load_reg_276 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln269_fu_184_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln269_reg_281 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln265_fu_160_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal m16_fu_66 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m16_1_fu_217_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal i_s4_0_fu_70 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln265_fu_154_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_i_s4_0_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal in_data_4_ce0_local : STD_LOGIC;
    signal in_data_14_ce0_local : STD_LOGIC;
    signal sext_ln267_fu_171_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal m120_fu_175_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln269_fu_180_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln268_fu_192_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal m121_fu_195_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln269_2_fu_204_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln269_1_fu_200_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln269_1_fu_207_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln269_3_fu_213_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component case_9_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component case_9_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_s4_0_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln265_fu_148_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_s4_0_fu_70 <= add_ln265_fu_154_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_s4_0_fu_70 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    m16_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    m16_fu_66 <= m16_17;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    m16_fu_66 <= m16_1_fu_217_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln269_reg_281 <= add_ln269_fu_184_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln265_reg_262 <= icmp_ln265_fu_148_p2;
                in_data_14_load_reg_276 <= in_data_14_q0;
                sext_ln22_3_cast_reg_257 <= sext_ln22_3_cast_fu_131_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln265_fu_154_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_s4_0_1) + unsigned(ap_const_lv4_1));
    add_ln269_1_fu_207_p2 <= std_logic_vector(signed(sext_ln269_2_fu_204_p1) + signed(sext_ln269_1_fu_200_p1));
    add_ln269_fu_184_p2 <= std_logic_vector(signed(sext_ln269_fu_180_p1) + signed(sext_ln22_3_cast_reg_257));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln265_fu_148_p2)
    begin
        if (((icmp_ln265_fu_148_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_s4_0_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_s4_0_fu_70)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_s4_0_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_s4_0_1 <= i_s4_0_fu_70;
        end if; 
    end process;

    icmp_ln265_fu_148_p2 <= "1" when (ap_sig_allocacmp_i_s4_0_1 = ap_const_lv4_8) else "0";
    in_data_14_address0 <= zext_ln265_fu_160_p1(4 - 1 downto 0);
    in_data_14_ce0 <= in_data_14_ce0_local;

    in_data_14_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_data_14_ce0_local <= ap_const_logic_1;
        else 
            in_data_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_data_4_address0 <= zext_ln265_fu_160_p1(4 - 1 downto 0);
    in_data_4_ce0 <= in_data_4_ce0_local;

    in_data_4_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_data_4_ce0_local <= ap_const_logic_1;
        else 
            in_data_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    m120_fu_175_p2 <= std_logic_vector(unsigned(mul_i1148_phi) + unsigned(sext_ln267_fu_171_p1));
    m121_fu_195_p2 <= std_logic_vector(unsigned(phi_ln130) + unsigned(sext_ln268_fu_192_p1));
    m16_19_out <= m16_fu_66;

    m16_19_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln265_reg_262, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((icmp_ln265_reg_262 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            m16_19_out_ap_vld <= ap_const_logic_1;
        else 
            m16_19_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m16_1_fu_217_p2 <= std_logic_vector(unsigned(m16_fu_66) + unsigned(sext_ln269_3_fu_213_p1));
        sext_ln22_3_cast_fu_131_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln22_3),8));

        sext_ln267_fu_171_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_data_4_q0),7));

        sext_ln268_fu_192_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_data_14_load_reg_276),10));

        sext_ln269_1_fu_200_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m121_fu_195_p2),11));

        sext_ln269_2_fu_204_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln269_reg_281),11));

        sext_ln269_3_fu_213_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln269_1_fu_207_p2),32));

        sext_ln269_fu_180_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m120_fu_175_p2),8));

    zext_ln265_fu_160_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_s4_0_1),64));
end behav;
