-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity case_3_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m27_15_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    m64_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    m64_ce0 : OUT STD_LOGIC;
    m64_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    sext_ln228 : IN STD_LOGIC_VECTOR (7 downto 0);
    conv3_i12_i132751 : IN STD_LOGIC_VECTOR (7 downto 0);
    m27_17_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    m27_17_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of case_3_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv8_40 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln225_fu_154_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal conv3_i12_i132751_cast_fu_118_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal conv3_i12_i132751_cast_reg_366 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln228_cast_fu_122_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln228_cast_reg_371 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln225_reg_376 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln225_reg_376_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln226_fu_169_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln226_reg_380 : STD_LOGIC_VECTOR (0 downto 0);
    signal m110_fu_299_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal m110_reg_392 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln228_1_fu_278_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal m27_fu_60 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal m27_12_fu_315_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal i_n10_2_fu_64 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln227_fu_283_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_n10_1_fu_68 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln226_fu_248_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten96_fu_72 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln226_1_fu_181_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten96_load : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten109_fu_76 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln225_fu_160_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten109_load : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal m64_ce0_local : STD_LOGIC;
    signal add_ln226_1_fu_175_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln227_fu_217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln22_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln22_fu_205_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln22_fu_223_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln22_fu_235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln226_fu_229_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln228_fu_256_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln22_1_fu_240_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_260_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln228_fu_268_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln228_fu_272_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal m110_fu_299_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln230_fu_307_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln230_fu_310_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component case_3_mul_15s_8s_15_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (14 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component case_3_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_15s_8s_15_1_1_U90 : component case_3_mul_15s_8s_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 8,
        dout_WIDTH => 15)
    port map (
        din0 => m64_q0,
        din1 => m110_fu_299_p1,
        dout => m110_fu_299_p2);

    flow_control_loop_pipe_sequential_init_U : component case_3_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    i_n10_1_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_n10_1_fu_68 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_n10_1_fu_68 <= select_ln226_fu_248_p3;
                end if;
            end if; 
        end if;
    end process;

    i_n10_2_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_n10_2_fu_64 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_n10_2_fu_64 <= add_ln227_fu_283_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten109_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln225_fu_154_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten109_fu_76 <= add_ln225_fu_160_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten109_fu_76 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten96_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln225_fu_154_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten96_fu_72 <= select_ln226_1_fu_181_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten96_fu_72 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    m27_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    m27_fu_60 <= m27_15_reload;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    m27_fu_60 <= m27_12_fu_315_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                conv3_i12_i132751_cast_reg_366 <= conv3_i12_i132751_cast_fu_118_p1;
                icmp_ln225_reg_376 <= icmp_ln225_fu_154_p2;
                icmp_ln225_reg_376_pp0_iter1_reg <= icmp_ln225_reg_376;
                icmp_ln226_reg_380 <= icmp_ln226_fu_169_p2;
                sext_ln228_cast_reg_371 <= sext_ln228_cast_fu_122_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                m110_reg_392 <= m110_fu_299_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln225_fu_160_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten109_load) + unsigned(ap_const_lv10_1));
    add_ln226_1_fu_175_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten96_load) + unsigned(ap_const_lv8_1));
    add_ln226_fu_229_p2 <= std_logic_vector(unsigned(select_ln22_fu_205_p3) + unsigned(ap_const_lv4_1));
    add_ln227_fu_283_p2 <= std_logic_vector(unsigned(select_ln22_1_fu_240_p3) + unsigned(ap_const_lv4_1));
    add_ln228_fu_272_p2 <= std_logic_vector(unsigned(tmp_4_fu_260_p3) + unsigned(zext_ln228_fu_268_p1));
    add_ln230_fu_310_p2 <= std_logic_vector(signed(conv3_i12_i132751_cast_reg_366) + signed(sext_ln230_fu_307_p1));
    and_ln22_fu_223_p2 <= (xor_ln22_fu_212_p2 and icmp_ln227_fu_217_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln225_fu_154_p2)
    begin
        if (((icmp_ln225_fu_154_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter2_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten109_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten109_fu_76)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten109_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten109_load <= indvar_flatten109_fu_76;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten96_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten96_fu_72)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten96_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten96_load <= indvar_flatten96_fu_72;
        end if; 
    end process;

        conv3_i12_i132751_cast_fu_118_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv3_i12_i132751),16));

    icmp_ln225_fu_154_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten109_load = ap_const_lv10_200) else "0";
    icmp_ln226_fu_169_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten96_load = ap_const_lv8_40) else "0";
    icmp_ln227_fu_217_p2 <= "1" when (i_n10_2_fu_64 = ap_const_lv4_8) else "0";
    m110_fu_299_p1 <= sext_ln228_cast_reg_371(8 - 1 downto 0);
    m27_12_fu_315_p2 <= std_logic_vector(unsigned(m27_fu_60) + unsigned(add_ln230_fu_310_p2));
    m27_17_out <= m27_fu_60;

    m27_17_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln225_reg_376_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((icmp_ln225_reg_376_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            m27_17_out_ap_vld <= ap_const_logic_1;
        else 
            m27_17_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m64_address0 <= zext_ln228_1_fu_278_p1(6 - 1 downto 0);
    m64_ce0 <= m64_ce0_local;

    m64_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m64_ce0_local <= ap_const_logic_1;
        else 
            m64_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    or_ln22_fu_235_p2 <= (icmp_ln226_reg_380 or and_ln22_fu_223_p2);
    select_ln226_1_fu_181_p3 <= 
        ap_const_lv8_1 when (icmp_ln226_fu_169_p2(0) = '1') else 
        add_ln226_1_fu_175_p2;
    select_ln226_fu_248_p3 <= 
        add_ln226_fu_229_p2 when (and_ln22_fu_223_p2(0) = '1') else 
        select_ln22_fu_205_p3;
    select_ln22_1_fu_240_p3 <= 
        ap_const_lv4_0 when (or_ln22_fu_235_p2(0) = '1') else 
        i_n10_2_fu_64;
    select_ln22_fu_205_p3 <= 
        ap_const_lv4_0 when (icmp_ln226_reg_380(0) = '1') else 
        i_n10_1_fu_68;
        sext_ln228_cast_fu_122_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln228),15));

        sext_ln230_fu_307_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m110_reg_392),16));

    tmp_4_fu_260_p3 <= (trunc_ln228_fu_256_p1 & ap_const_lv3_0);
    trunc_ln228_fu_256_p1 <= select_ln226_fu_248_p3(3 - 1 downto 0);
    xor_ln22_fu_212_p2 <= (icmp_ln226_reg_380 xor ap_const_lv1_1);
    zext_ln228_1_fu_278_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln228_fu_272_p2),64));
    zext_ln228_fu_268_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln22_1_fu_240_p3),6));
end behav;
