-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity case_3_case_3_Pipeline_L_n3_1_L_n3_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m27_1_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    in_data_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in_data_0_ce0 : OUT STD_LOGIC;
    in_data_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_data_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in_data_6_ce0 : OUT STD_LOGIC;
    in_data_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_data_10_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in_data_10_ce0 : OUT STD_LOGIC;
    in_data_10_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_data_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in_data_2_ce0 : OUT STD_LOGIC;
    in_data_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_data_14_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in_data_14_ce0 : OUT STD_LOGIC;
    in_data_14_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_scalar_load_2_cast : IN STD_LOGIC_VECTOR (3 downto 0);
    in_data_8_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in_data_8_ce0 : OUT STD_LOGIC;
    in_data_8_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_data_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in_data_4_ce0 : OUT STD_LOGIC;
    in_data_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    m43_cast70 : IN STD_LOGIC_VECTOR (4 downto 0);
    mul_i4971_cast : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln108_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    m27_2_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    m27_2_out_ap_vld : OUT STD_LOGIC;
    add_i5025_phi_out : OUT STD_LOGIC_VECTOR (8 downto 0);
    add_i5025_phi_out_ap_vld : OUT STD_LOGIC;
    add_i4863_phi_out : OUT STD_LOGIC_VECTOR (8 downto 0);
    add_i4863_phi_out_ap_vld : OUT STD_LOGIC;
    phi_ln127_out : OUT STD_LOGIC_VECTOR (2 downto 0);
    phi_ln127_out_ap_vld : OUT STD_LOGIC;
    conv3_i_i4798204_phi_out : OUT STD_LOGIC_VECTOR (8 downto 0);
    conv3_i_i4798204_phi_out_ap_vld : OUT STD_LOGIC;
    add_i4277_phi_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    add_i4277_phi_out_ap_vld : OUT STD_LOGIC;
    conv3_i12_i4097189_phi_out : OUT STD_LOGIC_VECTOR (2 downto 0);
    conv3_i12_i4097189_phi_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of case_3_case_3_Pipeline_L_n3_1_L_n3_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln108_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln108_1_cast_fu_288_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln108_1_cast_reg_628 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_i4971_cast_cast_fu_292_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_i4971_cast_cast_reg_633 : STD_LOGIC_VECTOR (8 downto 0);
    signal in_scalar_load_2_cast_cast_fu_296_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_scalar_load_2_cast_cast_reg_638 : STD_LOGIC_VECTOR (7 downto 0);
    signal m43_cast70_cast_fu_300_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal m43_cast70_cast_reg_643 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln108_reg_648 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_reg_648_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln109_fu_351_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln109_reg_652 : STD_LOGIC_VECTOR (63 downto 0);
    signal m39_reg_679 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_data_10_load_reg_689 : STD_LOGIC_VECTOR (7 downto 0);
    signal m46_fu_383_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal m46_reg_699 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln128_5_fu_405_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln128_5_reg_709 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln128_fu_462_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln128_reg_714 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln128_2_fu_476_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln128_2_reg_719 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln128_7_fu_500_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln128_7_reg_724 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal add_i4277_phi_fu_90 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal m47_fu_453_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal phi_ln127_fu_94 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal m49_fu_393_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_i4863_phi_fu_98 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal m40_fu_436_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_i5025_phi_fu_102 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal m37_fu_423_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal m27_2_fu_106 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal m27_fu_549_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_n3_1_fu_110 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln109_fu_359_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_i_n3_1_load : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten21_fu_114 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln108_fu_328_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_indvar_flatten21_load : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal in_data_0_ce0_local : STD_LOGIC;
    signal in_data_10_ce0_local : STD_LOGIC;
    signal in_data_8_ce0_local : STD_LOGIC;
    signal in_data_4_ce0_local : STD_LOGIC;
    signal in_data_6_ce0_local : STD_LOGIC;
    signal in_data_2_ce0_local : STD_LOGIC;
    signal in_data_14_ce0_local : STD_LOGIC;
    signal icmp_ln109_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln22_fu_343_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln122_fu_375_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln122_1_fu_379_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal m46_fu_383_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal m46_fu_383_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal m48_fu_389_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln128_1_fu_401_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln128_fu_397_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln110_1_fu_419_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln110_fu_416_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln113_1_fu_432_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln113_fu_429_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln122_fu_446_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln128_1_fu_467_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln128_3_fu_472_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln114_fu_442_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln126_fu_458_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln124_fu_450_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln128_5_fu_488_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln128_6_fu_491_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln128_6_fu_496_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln128_4_fu_482_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln128_4_fu_527_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln128_2_fu_524_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln128_7_fu_536_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln128_3_fu_530_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln128_8_fu_539_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln128_8_fu_545_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component case_3_mul_5s_5s_5_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component case_3_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_5s_5s_5_1_1_U8 : component case_3_mul_5s_5s_5_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 5,
        dout_WIDTH => 5)
    port map (
        din0 => m46_fu_383_p0,
        din1 => m46_fu_383_p1,
        dout => m46_fu_383_p2);

    flow_control_loop_pipe_sequential_init_U : component case_3_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    i_n3_1_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln108_fu_322_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_n3_1_fu_110 <= add_ln109_fu_359_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_n3_1_fu_110 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten21_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln108_fu_322_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten21_fu_114 <= add_ln108_fu_328_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten21_fu_114 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    m27_2_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    m27_2_fu_106 <= m27_1_reload;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    m27_2_fu_106 <= m27_fu_549_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                add_i4277_phi_fu_90 <= m47_fu_453_p2;
                add_i4863_phi_fu_98 <= m40_fu_436_p2;
                add_i5025_phi_fu_102 <= m37_fu_423_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln128_2_reg_719 <= add_ln128_2_fu_476_p2;
                add_ln128_7_reg_724 <= add_ln128_7_fu_500_p2;
                add_ln128_reg_714 <= add_ln128_fu_462_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln128_5_reg_709 <= add_ln128_5_fu_405_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln108_reg_648 <= icmp_ln108_fu_322_p2;
                icmp_ln108_reg_648_pp0_iter1_reg <= icmp_ln108_reg_648;
                in_data_10_load_reg_689 <= in_data_10_q0;
                in_scalar_load_2_cast_cast_reg_638 <= in_scalar_load_2_cast_cast_fu_296_p1;
                m39_reg_679 <= in_data_0_q0;
                m43_cast70_cast_reg_643 <= m43_cast70_cast_fu_300_p1;
                m46_reg_699 <= m46_fu_383_p2;
                mul_i4971_cast_cast_reg_633 <= mul_i4971_cast_cast_fu_292_p1;
                sext_ln108_1_cast_reg_628 <= sext_ln108_1_cast_fu_288_p1;
                    zext_ln109_reg_652(3 downto 0) <= zext_ln109_fu_351_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                phi_ln127_fu_94 <= m49_fu_393_p1;
            end if;
        end if;
    end process;
    zext_ln109_reg_652(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_i4277_phi_out <= add_i4277_phi_fu_90;

    add_i4277_phi_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln108_reg_648_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln108_reg_648_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i4277_phi_out_ap_vld <= ap_const_logic_1;
        else 
            add_i4277_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_i4863_phi_out <= add_i4863_phi_fu_98;

    add_i4863_phi_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln108_reg_648_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln108_reg_648_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i4863_phi_out_ap_vld <= ap_const_logic_1;
        else 
            add_i4863_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_i5025_phi_out <= add_i5025_phi_fu_102;

    add_i5025_phi_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln108_reg_648_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln108_reg_648_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i5025_phi_out_ap_vld <= ap_const_logic_1;
        else 
            add_i5025_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln108_fu_328_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten21_load) + unsigned(ap_const_lv7_1));
    add_ln109_fu_359_p2 <= std_logic_vector(unsigned(select_ln22_fu_343_p3) + unsigned(ap_const_lv4_1));
    add_ln128_1_fu_467_p2 <= std_logic_vector(signed(mul_i4971_cast_cast_reg_633) + signed(sext_ln110_fu_416_p1));
    add_ln128_2_fu_476_p2 <= std_logic_vector(signed(sext_ln128_3_fu_472_p1) + signed(sext_ln114_fu_442_p1));
    add_ln128_3_fu_530_p2 <= std_logic_vector(signed(sext_ln128_4_fu_527_p1) + signed(sext_ln128_2_fu_524_p1));
    add_ln128_4_fu_482_p2 <= std_logic_vector(signed(sext_ln126_fu_458_p1) + signed(sext_ln124_fu_450_p1));
    add_ln128_5_fu_405_p2 <= std_logic_vector(signed(sext_ln128_1_fu_401_p1) + signed(sext_ln128_fu_397_p1));
    add_ln128_6_fu_491_p2 <= std_logic_vector(signed(sext_ln128_5_fu_488_p1) + signed(sext_ln108_1_cast_reg_628));
    add_ln128_7_fu_500_p2 <= std_logic_vector(signed(sext_ln128_6_fu_496_p1) + signed(add_ln128_4_fu_482_p2));
    add_ln128_8_fu_539_p2 <= std_logic_vector(signed(sext_ln128_7_fu_536_p1) + signed(add_ln128_3_fu_530_p2));
    add_ln128_fu_462_p2 <= std_logic_vector(signed(m43_cast70_cast_reg_643) + signed(sext_ln122_fu_446_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln108_fu_322_p2)
    begin
        if (((icmp_ln108_fu_322_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter2_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_n3_1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_n3_1_fu_110)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_n3_1_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_n3_1_load <= i_n3_1_fu_110;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten21_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten21_fu_114)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten21_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_indvar_flatten21_load <= indvar_flatten21_fu_114;
        end if; 
    end process;

    conv3_i12_i4097189_phi_out <= phi_ln127_fu_94;

    conv3_i12_i4097189_phi_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln108_reg_648_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln108_reg_648_pp0_iter1_reg = ap_const_lv1_1))) then 
            conv3_i12_i4097189_phi_out_ap_vld <= ap_const_logic_1;
        else 
            conv3_i12_i4097189_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    conv3_i_i4798204_phi_out <= add_i5025_phi_fu_102;

    conv3_i_i4798204_phi_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln108_reg_648_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln108_reg_648_pp0_iter1_reg = ap_const_lv1_1))) then 
            conv3_i_i4798204_phi_out_ap_vld <= ap_const_logic_1;
        else 
            conv3_i_i4798204_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln108_fu_322_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten21_load = ap_const_lv7_40) else "0";
    icmp_ln109_fu_337_p2 <= "1" when (ap_sig_allocacmp_i_n3_1_load = ap_const_lv4_8) else "0";
    in_data_0_address0 <= zext_ln109_fu_351_p1(4 - 1 downto 0);
    in_data_0_ce0 <= in_data_0_ce0_local;

    in_data_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_data_0_ce0_local <= ap_const_logic_1;
        else 
            in_data_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_data_10_address0 <= zext_ln109_fu_351_p1(4 - 1 downto 0);
    in_data_10_ce0 <= in_data_10_ce0_local;

    in_data_10_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_data_10_ce0_local <= ap_const_logic_1;
        else 
            in_data_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_data_14_address0 <= zext_ln109_reg_652(4 - 1 downto 0);
    in_data_14_ce0 <= in_data_14_ce0_local;

    in_data_14_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_data_14_ce0_local <= ap_const_logic_1;
        else 
            in_data_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_data_2_address0 <= zext_ln109_reg_652(4 - 1 downto 0);
    in_data_2_ce0 <= in_data_2_ce0_local;

    in_data_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_data_2_ce0_local <= ap_const_logic_1;
        else 
            in_data_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_data_4_address0 <= zext_ln109_fu_351_p1(4 - 1 downto 0);
    in_data_4_ce0 <= in_data_4_ce0_local;

    in_data_4_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_data_4_ce0_local <= ap_const_logic_1;
        else 
            in_data_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_data_6_address0 <= zext_ln109_reg_652(4 - 1 downto 0);
    in_data_6_ce0 <= in_data_6_ce0_local;

    in_data_6_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_data_6_ce0_local <= ap_const_logic_1;
        else 
            in_data_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_data_8_address0 <= zext_ln109_fu_351_p1(4 - 1 downto 0);
    in_data_8_ce0 <= in_data_8_ce0_local;

    in_data_8_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_data_8_ce0_local <= ap_const_logic_1;
        else 
            in_data_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

        in_scalar_load_2_cast_cast_fu_296_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_scalar_load_2_cast),8));

    m27_2_out <= m27_2_fu_106;

    m27_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln108_reg_648_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln108_reg_648_pp0_iter1_reg = ap_const_lv1_1))) then 
            m27_2_out_ap_vld <= ap_const_logic_1;
        else 
            m27_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m27_fu_549_p2 <= std_logic_vector(unsigned(m27_2_fu_106) + unsigned(sext_ln128_8_fu_545_p1));
    m37_fu_423_p2 <= std_logic_vector(signed(sext_ln110_1_fu_419_p1) + signed(sext_ln110_fu_416_p1));
    m40_fu_436_p2 <= std_logic_vector(signed(sext_ln113_1_fu_432_p1) + signed(sext_ln113_fu_429_p1));
        m43_cast70_cast_fu_300_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m43_cast70),10));

    m46_fu_383_p0 <= trunc_ln122_1_fu_379_p0(5 - 1 downto 0);
    m46_fu_383_p1 <= trunc_ln122_fu_375_p0(5 - 1 downto 0);
    m47_fu_453_p2 <= std_logic_vector(unsigned(in_data_14_q0) + unsigned(in_scalar_load_2_cast_cast_reg_638));
    m48_fu_389_p1 <= in_data_8_q0(2 - 1 downto 0);
    m49_fu_393_p1 <= in_data_4_q0(3 - 1 downto 0);
        mul_i4971_cast_cast_fu_292_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_i4971_cast),9));

    phi_ln127_out <= phi_ln127_fu_94;

    phi_ln127_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln108_reg_648_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln108_reg_648_pp0_iter1_reg = ap_const_lv1_1))) then 
            phi_ln127_out_ap_vld <= ap_const_logic_1;
        else 
            phi_ln127_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln22_fu_343_p3 <= 
        ap_const_lv4_0 when (icmp_ln109_fu_337_p2(0) = '1') else 
        ap_sig_allocacmp_i_n3_1_load;
        sext_ln108_1_cast_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln108_1),5));

        sext_ln110_1_fu_419_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_data_6_q0),9));

        sext_ln110_fu_416_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m39_reg_679),9));

        sext_ln113_1_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_data_2_q0),9));

        sext_ln113_fu_429_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_data_10_load_reg_689),9));

        sext_ln114_fu_442_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m37_fu_423_p2),10));

        sext_ln122_fu_446_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m40_fu_436_p2),10));

        sext_ln124_fu_450_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m46_reg_699),9));

        sext_ln126_fu_458_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m47_fu_453_p2),9));

        sext_ln128_1_fu_401_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m49_fu_393_p1),4));

        sext_ln128_2_fu_524_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln128_reg_714),11));

        sext_ln128_3_fu_472_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln128_1_fu_467_p2),10));

        sext_ln128_4_fu_527_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln128_2_reg_719),11));

        sext_ln128_5_fu_488_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln128_5_reg_709),5));

        sext_ln128_6_fu_496_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln128_6_fu_491_p2),9));

        sext_ln128_7_fu_536_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln128_7_reg_724),11));

        sext_ln128_8_fu_545_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln128_8_fu_539_p2),16));

        sext_ln128_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m48_fu_389_p1),4));

    trunc_ln122_1_fu_379_p0 <= in_data_10_q0;
    trunc_ln122_fu_375_p0 <= in_data_0_q0;
    zext_ln109_fu_351_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln22_fu_343_p3),64));
end behav;
