-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity case_3_case_3_Pipeline_L_m1_1_L_m1_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_data_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in_data_0_ce0 : OUT STD_LOGIC;
    in_data_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_data_0_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in_data_0_ce1 : OUT STD_LOGIC;
    in_data_0_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    m64_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    m64_ce0 : OUT STD_LOGIC;
    m64_we0 : OUT STD_LOGIC;
    m64_d0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    in_data_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in_data_2_ce0 : OUT STD_LOGIC;
    in_data_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_data_2_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in_data_2_ce1 : OUT STD_LOGIC;
    in_data_2_q1 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of case_3_case_3_Pipeline_L_m1_1_L_m1_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln151_reg_984 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal icmp_ln151_fu_255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln151_fu_285_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln151_reg_988 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln153_fu_301_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln153_reg_993 : STD_LOGIC_VECTOR (2 downto 0);
    signal bit_sel1_reg_1013 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_329_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_reg_1018 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_11_fu_333_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_11_reg_1023 : STD_LOGIC_VECTOR (2 downto 0);
    signal bit_sel_reg_1042 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln158_fu_361_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln158_reg_1047 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal mul_ln155_fu_418_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln155_reg_1062 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln156_fu_428_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln156_reg_1068 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal mul_ln157_fu_493_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln157_reg_1094 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln158_fu_503_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln158_reg_1100 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal add_ln153_fu_574_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln153_reg_1126 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln158_1_fu_584_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln158_1_reg_1131 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln158_2_fu_594_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln158_2_reg_1137 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln158_3_fu_632_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln158_3_reg_1153 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln158_4_fu_642_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln158_4_reg_1159 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln159_24_fu_904_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln159_24_reg_1165 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln159_25_fu_910_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln159_25_reg_1170 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln159_27_fu_916_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln159_27_reg_1175 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln159_28_fu_922_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln159_28_reg_1180 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln155_fu_305_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal idxprom3402_fu_316_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln155_1_fu_337_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln156_fu_348_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal idxprom3563_fu_399_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal idxprom3724_fu_409_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln157_fu_439_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln158_fu_449_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal idxprom372_15_fu_474_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal idxprom372_26_fu_484_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln158_1_fu_521_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln158_2_fu_531_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal idxprom372_37_fu_556_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal idxprom372_48_fu_566_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln158_3_fu_605_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln158_4_fu_615_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln153_1_fu_928_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_66 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln152_fu_365_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (3 downto 0);
    signal i_fu_70 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln151_1_fu_293_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten57_fu_74 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln151_1_fu_261_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_indvar_flatten57_load : STD_LOGIC_VECTOR (6 downto 0);
    signal in_data_0_ce1_local : STD_LOGIC;
    signal in_data_0_address1_local : STD_LOGIC_VECTOR (3 downto 0);
    signal in_data_0_ce0_local : STD_LOGIC;
    signal in_data_0_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal in_data_2_ce1_local : STD_LOGIC;
    signal in_data_2_address1_local : STD_LOGIC_VECTOR (3 downto 0);
    signal in_data_2_ce0_local : STD_LOGIC;
    signal in_data_2_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal m64_we0_local : STD_LOGIC;
    signal add_ln159_30_fu_956_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal m64_ce0_local : STD_LOGIC;
    signal icmp_ln152_fu_279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln151_fu_273_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add338_fu_310_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln156_fu_342_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add354_fu_394_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add370_fu_404_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln157_fu_434_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln158_fu_444_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal xor_val143_fu_462_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add370_1_fu_467_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal add370_2_fu_479_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal xor_ln158_fu_509_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln_fu_514_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln158_1_fu_526_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add370_3_fu_551_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add370_4_fu_561_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_536_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln153_fu_571_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln158_2_fu_600_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln158_3_fu_610_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln159_1_fu_651_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln159_fu_648_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln159_fu_654_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln159_2_fu_660_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln159_3_fu_664_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln159_1_fu_667_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln159_4_fu_673_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln159_2_fu_676_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln159_5_fu_686_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln159_3_fu_689_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln159_6_fu_695_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln159_4_fu_699_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln159_7_fu_705_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln159_5_fu_708_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln159_8_fu_718_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln159_6_fu_721_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln159_9_fu_727_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln159_7_fu_731_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln159_10_fu_737_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln159_8_fu_740_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln159_11_fu_750_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln159_9_fu_753_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln159_12_fu_759_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln159_10_fu_763_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln159_13_fu_769_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln159_11_fu_772_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln159_14_fu_782_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln159_12_fu_785_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln159_15_fu_791_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln159_13_fu_795_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln159_16_fu_801_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln159_14_fu_804_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln159_18_fu_814_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln159_15_fu_817_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln159_19_fu_823_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln159_16_fu_827_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln159_20_fu_833_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln159_17_fu_836_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln159_22_fu_846_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln159_18_fu_849_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln159_23_fu_855_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln159_19_fu_859_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln159_24_fu_865_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln159_20_fu_868_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln159_21_fu_878_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln159_26_fu_884_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln159_22_fu_888_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln159_23_fu_894_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln158_11_fu_714_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln158_10_fu_682_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln158_12_fu_746_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln158_13_fu_778_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln159_17_fu_810_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln159_21_fu_842_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln159_25_fu_874_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln159_27_fu_900_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln159_29_fu_935_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln159_28_fu_932_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln159_31_fu_947_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln159_30_fu_944_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln159_29_fu_950_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln159_26_fu_938_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component case_3_mul_8s_8s_11_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component case_3_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_8s_8s_11_1_1_U40 : component case_3_mul_8s_8s_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 11)
    port map (
        din0 => in_data_2_q1,
        din1 => in_data_0_q1,
        dout => mul_ln155_fu_418_p2);

    mul_8s_8s_11_1_1_U41 : component case_3_mul_8s_8s_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 11)
    port map (
        din0 => in_data_2_q0,
        din1 => in_data_0_q0,
        dout => mul_ln156_fu_428_p2);

    mul_8s_8s_11_1_1_U42 : component case_3_mul_8s_8s_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 11)
    port map (
        din0 => in_data_2_q1,
        din1 => in_data_0_q1,
        dout => mul_ln157_fu_493_p2);

    mul_8s_8s_11_1_1_U43 : component case_3_mul_8s_8s_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 11)
    port map (
        din0 => in_data_2_q0,
        din1 => in_data_0_q0,
        dout => mul_ln158_fu_503_p2);

    mul_8s_8s_11_1_1_U44 : component case_3_mul_8s_8s_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 11)
    port map (
        din0 => in_data_2_q1,
        din1 => in_data_0_q1,
        dout => mul_ln158_1_fu_584_p2);

    mul_8s_8s_11_1_1_U45 : component case_3_mul_8s_8s_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 11)
    port map (
        din0 => in_data_2_q0,
        din1 => in_data_0_q0,
        dout => mul_ln158_2_fu_594_p2);

    mul_8s_8s_11_1_1_U46 : component case_3_mul_8s_8s_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 11)
    port map (
        din0 => in_data_2_q1,
        din1 => in_data_0_q1,
        dout => mul_ln158_3_fu_632_p2);

    mul_8s_8s_11_1_1_U47 : component case_3_mul_8s_8s_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 11)
    port map (
        din0 => in_data_2_q0,
        din1 => in_data_0_q0,
        dout => mul_ln158_4_fu_642_p2);

    flow_control_loop_pipe_sequential_init_U : component case_3_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln151_fu_255_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_70 <= select_ln151_1_fu_293_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_70 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten57_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln151_fu_255_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten57_fu_74 <= add_ln151_1_fu_261_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten57_fu_74 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln151_fu_255_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_66 <= add_ln152_fu_365_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_66 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                add_ln153_reg_1126 <= add_ln153_fu_574_p2;
                mul_ln158_1_reg_1131 <= mul_ln158_1_fu_584_p2;
                mul_ln158_2_reg_1137 <= mul_ln158_2_fu_594_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln159_24_reg_1165 <= add_ln159_24_fu_904_p2;
                add_ln159_25_reg_1170 <= add_ln159_25_fu_910_p2;
                add_ln159_27_reg_1175 <= add_ln159_27_fu_916_p2;
                add_ln159_28_reg_1180 <= add_ln159_28_fu_922_p2;
                mul_ln155_reg_1062 <= mul_ln155_fu_418_p2;
                mul_ln156_reg_1068 <= mul_ln156_fu_428_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                bit_sel1_reg_1013 <= select_ln151_1_fu_293_p3(2 downto 2);
                bit_sel_reg_1042 <= select_ln151_fu_285_p3(2 downto 2);
                empty_11_reg_1023 <= empty_11_fu_333_p1;
                empty_reg_1018 <= empty_fu_329_p1;
                icmp_ln151_reg_984 <= icmp_ln151_fu_255_p2;
                mul_ln158_3_reg_1153 <= mul_ln158_3_fu_632_p2;
                mul_ln158_4_reg_1159 <= mul_ln158_4_fu_642_p2;
                select_ln151_reg_988 <= select_ln151_fu_285_p3;
                trunc_ln153_reg_993 <= trunc_ln153_fu_301_p1;
                trunc_ln158_reg_1047 <= trunc_ln158_fu_361_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                mul_ln157_reg_1094 <= mul_ln157_fu_493_p2;
                mul_ln158_reg_1100 <= mul_ln158_fu_503_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_condition_exit_pp0_iter0_stage2, ap_block_pp0_stage3_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add338_fu_310_p2 <= std_logic_vector(unsigned(trunc_ln153_fu_301_p1) + unsigned(ap_const_lv3_1));
    add354_fu_394_p2 <= std_logic_vector(unsigned(trunc_ln153_reg_993) + unsigned(ap_const_lv3_2));
    add370_1_fu_467_p3 <= (xor_val143_fu_462_p2 & empty_reg_1018);
    add370_2_fu_479_p2 <= std_logic_vector(unsigned(trunc_ln153_reg_993) + unsigned(ap_const_lv3_5));
    add370_3_fu_551_p2 <= std_logic_vector(unsigned(trunc_ln153_reg_993) + unsigned(ap_const_lv3_6));
    add370_4_fu_561_p2 <= std_logic_vector(unsigned(trunc_ln153_reg_993) + unsigned(ap_const_lv3_7));
    add370_fu_404_p2 <= std_logic_vector(unsigned(trunc_ln153_reg_993) + unsigned(ap_const_lv3_3));
    add_ln151_1_fu_261_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten57_load) + unsigned(ap_const_lv7_1));
    add_ln151_fu_273_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv4_1));
    add_ln152_fu_365_p2 <= std_logic_vector(unsigned(select_ln151_fu_285_p3) + unsigned(ap_const_lv4_1));
    add_ln153_fu_574_p2 <= std_logic_vector(unsigned(tmp_3_fu_536_p3) + unsigned(zext_ln153_fu_571_p1));
    add_ln156_fu_342_p2 <= std_logic_vector(unsigned(empty_11_fu_333_p1) + unsigned(ap_const_lv3_1));
    add_ln157_fu_434_p2 <= std_logic_vector(unsigned(empty_11_reg_1023) + unsigned(ap_const_lv3_2));
    add_ln158_1_fu_526_p2 <= std_logic_vector(unsigned(empty_11_reg_1023) + unsigned(ap_const_lv3_5));
    add_ln158_2_fu_600_p2 <= std_logic_vector(unsigned(empty_11_reg_1023) + unsigned(ap_const_lv3_6));
    add_ln158_3_fu_610_p2 <= std_logic_vector(unsigned(empty_11_reg_1023) + unsigned(ap_const_lv3_7));
    add_ln158_fu_444_p2 <= std_logic_vector(unsigned(empty_11_reg_1023) + unsigned(ap_const_lv3_3));
    add_ln159_10_fu_763_p2 <= std_logic_vector(signed(sext_ln159_12_fu_759_p1) + signed(sext_ln159_10_fu_737_p1));
    add_ln159_11_fu_772_p2 <= std_logic_vector(unsigned(add_ln159_10_fu_763_p2) + unsigned(sext_ln159_13_fu_769_p1));
    add_ln159_12_fu_785_p2 <= std_logic_vector(signed(sext_ln159_14_fu_782_p1) + signed(sext_ln159_11_fu_750_p1));
    add_ln159_13_fu_795_p2 <= std_logic_vector(signed(sext_ln159_15_fu_791_p1) + signed(sext_ln159_13_fu_769_p1));
    add_ln159_14_fu_804_p2 <= std_logic_vector(unsigned(add_ln159_13_fu_795_p2) + unsigned(sext_ln159_16_fu_801_p1));
    add_ln159_15_fu_817_p2 <= std_logic_vector(signed(sext_ln159_18_fu_814_p1) + signed(sext_ln159_14_fu_782_p1));
    add_ln159_16_fu_827_p2 <= std_logic_vector(signed(sext_ln159_19_fu_823_p1) + signed(sext_ln159_16_fu_801_p1));
    add_ln159_17_fu_836_p2 <= std_logic_vector(unsigned(add_ln159_16_fu_827_p2) + unsigned(sext_ln159_20_fu_833_p1));
    add_ln159_18_fu_849_p2 <= std_logic_vector(signed(sext_ln159_22_fu_846_p1) + signed(sext_ln159_18_fu_814_p1));
    add_ln159_19_fu_859_p2 <= std_logic_vector(signed(sext_ln159_23_fu_855_p1) + signed(sext_ln159_20_fu_833_p1));
    add_ln159_1_fu_667_p2 <= std_logic_vector(signed(sext_ln159_2_fu_660_p1) + signed(sext_ln159_3_fu_664_p1));
    add_ln159_20_fu_868_p2 <= std_logic_vector(unsigned(add_ln159_19_fu_859_p2) + unsigned(sext_ln159_24_fu_865_p1));
    add_ln159_21_fu_878_p2 <= std_logic_vector(signed(sext_ln159_22_fu_846_p1) + signed(sext_ln159_fu_648_p1));
    add_ln159_22_fu_888_p2 <= std_logic_vector(signed(sext_ln159_26_fu_884_p1) + signed(sext_ln159_24_fu_865_p1));
    add_ln159_23_fu_894_p2 <= std_logic_vector(unsigned(add_ln159_22_fu_888_p2) + unsigned(sext_ln159_3_fu_664_p1));
    add_ln159_24_fu_904_p2 <= std_logic_vector(signed(sext_ln158_11_fu_714_p1) + signed(sext_ln158_10_fu_682_p1));
    add_ln159_25_fu_910_p2 <= std_logic_vector(signed(sext_ln158_12_fu_746_p1) + signed(sext_ln158_13_fu_778_p1));
    add_ln159_26_fu_938_p2 <= std_logic_vector(signed(sext_ln159_29_fu_935_p1) + signed(sext_ln159_28_fu_932_p1));
    add_ln159_27_fu_916_p2 <= std_logic_vector(signed(sext_ln159_17_fu_810_p1) + signed(sext_ln159_21_fu_842_p1));
    add_ln159_28_fu_922_p2 <= std_logic_vector(signed(sext_ln159_25_fu_874_p1) + signed(sext_ln159_27_fu_900_p1));
    add_ln159_29_fu_950_p2 <= std_logic_vector(signed(sext_ln159_31_fu_947_p1) + signed(sext_ln159_30_fu_944_p1));
    add_ln159_2_fu_676_p2 <= std_logic_vector(unsigned(add_ln159_1_fu_667_p2) + unsigned(sext_ln159_4_fu_673_p1));
    add_ln159_30_fu_956_p2 <= std_logic_vector(unsigned(add_ln159_29_fu_950_p2) + unsigned(add_ln159_26_fu_938_p2));
    add_ln159_3_fu_689_p2 <= std_logic_vector(signed(sext_ln159_5_fu_686_p1) + signed(sext_ln159_1_fu_651_p1));
    add_ln159_4_fu_699_p2 <= std_logic_vector(signed(sext_ln159_6_fu_695_p1) + signed(sext_ln159_4_fu_673_p1));
    add_ln159_5_fu_708_p2 <= std_logic_vector(unsigned(add_ln159_4_fu_699_p2) + unsigned(sext_ln159_7_fu_705_p1));
    add_ln159_6_fu_721_p2 <= std_logic_vector(signed(sext_ln159_8_fu_718_p1) + signed(sext_ln159_5_fu_686_p1));
    add_ln159_7_fu_731_p2 <= std_logic_vector(signed(sext_ln159_9_fu_727_p1) + signed(sext_ln159_7_fu_705_p1));
    add_ln159_8_fu_740_p2 <= std_logic_vector(unsigned(add_ln159_7_fu_731_p2) + unsigned(sext_ln159_10_fu_737_p1));
    add_ln159_9_fu_753_p2 <= std_logic_vector(signed(sext_ln159_11_fu_750_p1) + signed(sext_ln159_8_fu_718_p1));
    add_ln159_fu_654_p2 <= std_logic_vector(signed(sext_ln159_1_fu_651_p1) + signed(sext_ln159_fu_648_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln151_reg_984)
    begin
        if (((icmp_ln151_reg_984 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_70)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_70;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten57_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten57_fu_74)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten57_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_indvar_flatten57_load <= indvar_flatten57_fu_74;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_66, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_j_load <= j_fu_66;
        end if; 
    end process;

    empty_11_fu_333_p1 <= select_ln151_fu_285_p3(3 - 1 downto 0);
    empty_fu_329_p1 <= select_ln151_1_fu_293_p3(2 - 1 downto 0);
    icmp_ln151_fu_255_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten57_load = ap_const_lv7_40) else "0";
    icmp_ln152_fu_279_p2 <= "1" when (ap_sig_allocacmp_j_load = ap_const_lv4_8) else "0";
    idxprom3402_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add338_fu_310_p2),64));
    idxprom3563_fu_399_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add354_fu_394_p2),64));
    idxprom3724_fu_409_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add370_fu_404_p2),64));
    idxprom372_15_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add370_1_fu_467_p3),64));
    idxprom372_26_fu_484_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add370_2_fu_479_p2),64));
    idxprom372_37_fu_556_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add370_3_fu_551_p2),64));
    idxprom372_48_fu_566_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add370_4_fu_561_p2),64));
    in_data_0_address0 <= in_data_0_address0_local;

    in_data_0_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, idxprom3402_fu_316_p1, ap_block_pp0_stage1, idxprom3724_fu_409_p1, ap_block_pp0_stage2, idxprom372_26_fu_484_p1, ap_block_pp0_stage3, idxprom372_48_fu_566_p1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            in_data_0_address0_local <= idxprom372_48_fu_566_p1(4 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            in_data_0_address0_local <= idxprom372_26_fu_484_p1(4 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            in_data_0_address0_local <= idxprom3724_fu_409_p1(4 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_data_0_address0_local <= idxprom3402_fu_316_p1(4 - 1 downto 0);
        else 
            in_data_0_address0_local <= "XXXX";
        end if; 
    end process;

    in_data_0_address1 <= in_data_0_address1_local;

    in_data_0_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, zext_ln155_fu_305_p1, ap_block_pp0_stage0, idxprom3563_fu_399_p1, ap_block_pp0_stage1, idxprom372_15_fu_474_p1, ap_block_pp0_stage2, idxprom372_37_fu_556_p1, ap_block_pp0_stage3)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            in_data_0_address1_local <= idxprom372_37_fu_556_p1(4 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            in_data_0_address1_local <= idxprom372_15_fu_474_p1(4 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            in_data_0_address1_local <= idxprom3563_fu_399_p1(4 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_data_0_address1_local <= zext_ln155_fu_305_p1(4 - 1 downto 0);
        else 
            in_data_0_address1_local <= "XXXX";
        end if; 
    end process;

    in_data_0_ce0 <= in_data_0_ce0_local;

    in_data_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            in_data_0_ce0_local <= ap_const_logic_1;
        else 
            in_data_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_data_0_ce1 <= in_data_0_ce1_local;

    in_data_0_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            in_data_0_ce1_local <= ap_const_logic_1;
        else 
            in_data_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    in_data_2_address0 <= in_data_2_address0_local;

    in_data_2_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln156_fu_348_p1, ap_block_pp0_stage1, zext_ln158_fu_449_p1, ap_block_pp0_stage2, zext_ln158_2_fu_531_p1, ap_block_pp0_stage3, zext_ln158_4_fu_615_p1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            in_data_2_address0_local <= zext_ln158_4_fu_615_p1(4 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            in_data_2_address0_local <= zext_ln158_2_fu_531_p1(4 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            in_data_2_address0_local <= zext_ln158_fu_449_p1(4 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_data_2_address0_local <= zext_ln156_fu_348_p1(4 - 1 downto 0);
        else 
            in_data_2_address0_local <= "XXXX";
        end if; 
    end process;

    in_data_2_address1 <= in_data_2_address1_local;

    in_data_2_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln155_1_fu_337_p1, ap_block_pp0_stage1, zext_ln157_fu_439_p1, ap_block_pp0_stage2, zext_ln158_1_fu_521_p1, ap_block_pp0_stage3, zext_ln158_3_fu_605_p1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            in_data_2_address1_local <= zext_ln158_3_fu_605_p1(4 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            in_data_2_address1_local <= zext_ln158_1_fu_521_p1(4 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            in_data_2_address1_local <= zext_ln157_fu_439_p1(4 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_data_2_address1_local <= zext_ln155_1_fu_337_p1(4 - 1 downto 0);
        else 
            in_data_2_address1_local <= "XXXX";
        end if; 
    end process;

    in_data_2_ce0 <= in_data_2_ce0_local;

    in_data_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            in_data_2_ce0_local <= ap_const_logic_1;
        else 
            in_data_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_data_2_ce1 <= in_data_2_ce1_local;

    in_data_2_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            in_data_2_ce1_local <= ap_const_logic_1;
        else 
            in_data_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    m64_address0 <= zext_ln153_1_fu_928_p1(6 - 1 downto 0);
    m64_ce0 <= m64_ce0_local;

    m64_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            m64_ce0_local <= ap_const_logic_1;
        else 
            m64_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    m64_d0 <= add_ln159_30_fu_956_p2;
    m64_we0 <= m64_we0_local;

    m64_we0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            m64_we0_local <= ap_const_logic_1;
        else 
            m64_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln151_1_fu_293_p3 <= 
        add_ln151_fu_273_p2 when (icmp_ln152_fu_279_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln151_fu_285_p3 <= 
        ap_const_lv4_0 when (icmp_ln152_fu_279_p2(0) = '1') else 
        ap_sig_allocacmp_j_load;
        sext_ln158_10_fu_682_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_2_fu_676_p2),14));

        sext_ln158_11_fu_714_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_5_fu_708_p2),14));

        sext_ln158_12_fu_746_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_8_fu_740_p2),14));

        sext_ln158_13_fu_778_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_11_fu_772_p2),14));

        sext_ln159_10_fu_737_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln158_2_reg_1137),13));

        sext_ln159_11_fu_750_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln158_1_reg_1131),12));

        sext_ln159_12_fu_759_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_9_fu_753_p2),13));

        sext_ln159_13_fu_769_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln158_3_reg_1153),13));

        sext_ln159_14_fu_782_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln158_2_reg_1137),12));

        sext_ln159_15_fu_791_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_12_fu_785_p2),13));

        sext_ln159_16_fu_801_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln158_4_reg_1159),13));

        sext_ln159_17_fu_810_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_14_fu_804_p2),14));

        sext_ln159_18_fu_814_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln158_3_reg_1153),12));

        sext_ln159_19_fu_823_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_15_fu_817_p2),13));

        sext_ln159_1_fu_651_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln156_reg_1068),12));

        sext_ln159_20_fu_833_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln155_reg_1062),13));

        sext_ln159_21_fu_842_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_17_fu_836_p2),14));

        sext_ln159_22_fu_846_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln158_4_reg_1159),12));

        sext_ln159_23_fu_855_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_18_fu_849_p2),13));

        sext_ln159_24_fu_865_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln156_reg_1068),13));

        sext_ln159_25_fu_874_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_20_fu_868_p2),14));

        sext_ln159_26_fu_884_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_21_fu_878_p2),13));

        sext_ln159_27_fu_900_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_23_fu_894_p2),14));

        sext_ln159_28_fu_932_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_24_reg_1165),15));

        sext_ln159_29_fu_935_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_25_reg_1170),15));

        sext_ln159_2_fu_660_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_fu_654_p2),13));

        sext_ln159_30_fu_944_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_27_reg_1175),15));

        sext_ln159_31_fu_947_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_28_reg_1180),15));

        sext_ln159_3_fu_664_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln157_reg_1094),13));

        sext_ln159_4_fu_673_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln158_reg_1100),13));

        sext_ln159_5_fu_686_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln157_reg_1094),12));

        sext_ln159_6_fu_695_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_3_fu_689_p2),13));

        sext_ln159_7_fu_705_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln158_1_reg_1131),13));

        sext_ln159_8_fu_718_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln158_reg_1100),12));

        sext_ln159_9_fu_727_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_6_fu_721_p2),13));

        sext_ln159_fu_648_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln155_reg_1062),12));

    tmp_3_fu_536_p3 <= (trunc_ln153_reg_993 & ap_const_lv3_0);
    trunc_ln153_fu_301_p1 <= select_ln151_1_fu_293_p3(3 - 1 downto 0);
    trunc_ln158_fu_361_p1 <= select_ln151_fu_285_p3(2 - 1 downto 0);
    xor_ln158_fu_509_p2 <= (bit_sel_reg_1042 xor ap_const_lv1_1);
    xor_ln_fu_514_p3 <= (xor_ln158_fu_509_p2 & trunc_ln158_reg_1047);
    xor_val143_fu_462_p2 <= (bit_sel1_reg_1013 xor ap_const_lv1_1);
    zext_ln153_1_fu_928_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln153_reg_1126),64));
    zext_ln153_fu_571_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln151_reg_988),6));
    zext_ln155_1_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_11_fu_333_p1),64));
    zext_ln155_fu_305_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln153_fu_301_p1),64));
    zext_ln156_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln156_fu_342_p2),64));
    zext_ln157_fu_439_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln157_fu_434_p2),64));
    zext_ln158_1_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln_fu_514_p3),64));
    zext_ln158_2_fu_531_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln158_1_fu_526_p2),64));
    zext_ln158_3_fu_605_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln158_2_fu_600_p2),64));
    zext_ln158_4_fu_615_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln158_3_fu_610_p2),64));
    zext_ln158_fu_449_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln158_fu_444_p2),64));
end behav;
