// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module case_3_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m27_15_reload,
        m64_address0,
        m64_ce0,
        m64_q0,
        sext_ln228,
        conv3_i12_i132751,
        m27_17_out,
        m27_17_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] m27_15_reload;
output  [5:0] m64_address0;
output   m64_ce0;
input  [14:0] m64_q0;
input  [7:0] sext_ln228;
input  [7:0] conv3_i12_i132751;
output  [15:0] m27_17_out;
output   m27_17_out_ap_vld;

reg ap_idle;
reg m27_17_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln225_fu_154_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [15:0] conv3_i12_i132751_cast_fu_118_p1;
reg  signed [15:0] conv3_i12_i132751_cast_reg_366;
wire  signed [14:0] sext_ln228_cast_fu_122_p1;
reg  signed [14:0] sext_ln228_cast_reg_371;
reg   [0:0] icmp_ln225_reg_376;
reg   [0:0] icmp_ln225_reg_376_pp0_iter1_reg;
wire   [0:0] icmp_ln226_fu_169_p2;
reg   [0:0] icmp_ln226_reg_380;
wire   [14:0] m110_fu_299_p2;
reg   [14:0] m110_reg_392;
wire   [63:0] zext_ln228_1_fu_278_p1;
wire    ap_block_pp0_stage0;
reg   [15:0] m27_fu_60;
wire   [15:0] m27_12_fu_315_p2;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [3:0] i_n10_2_fu_64;
wire   [3:0] add_ln227_fu_283_p2;
reg   [3:0] i_n10_1_fu_68;
wire   [3:0] select_ln226_fu_248_p3;
reg   [7:0] indvar_flatten96_fu_72;
wire   [7:0] select_ln226_1_fu_181_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten96_load;
reg   [9:0] indvar_flatten109_fu_76;
wire   [9:0] add_ln225_fu_160_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten109_load;
wire    ap_block_pp0_stage0_01001;
reg    m64_ce0_local;
wire   [7:0] add_ln226_1_fu_175_p2;
wire   [0:0] icmp_ln227_fu_217_p2;
wire   [0:0] xor_ln22_fu_212_p2;
wire   [3:0] select_ln22_fu_205_p3;
wire   [0:0] and_ln22_fu_223_p2;
wire   [0:0] or_ln22_fu_235_p2;
wire   [3:0] add_ln226_fu_229_p2;
wire   [2:0] trunc_ln228_fu_256_p1;
wire   [3:0] select_ln22_1_fu_240_p3;
wire   [5:0] tmp_4_fu_260_p3;
wire   [5:0] zext_ln228_fu_268_p1;
wire   [5:0] add_ln228_fu_272_p2;
wire  signed [7:0] m110_fu_299_p1;
wire  signed [15:0] sext_ln230_fu_307_p1;
wire   [15:0] add_ln230_fu_310_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 m27_fu_60 = 16'd0;
#0 i_n10_2_fu_64 = 4'd0;
#0 i_n10_1_fu_68 = 4'd0;
#0 indvar_flatten96_fu_72 = 8'd0;
#0 indvar_flatten109_fu_76 = 10'd0;
#0 ap_done_reg = 1'b0;
end

case_3_mul_15s_8s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_15s_8s_15_1_1_U90(
    .din0(m64_q0),
    .din1(m110_fu_299_p1),
    .dout(m110_fu_299_p2)
);

case_3_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_n10_1_fu_68 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_n10_1_fu_68 <= select_ln226_fu_248_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_n10_2_fu_64 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_n10_2_fu_64 <= add_ln227_fu_283_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln225_fu_154_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten109_fu_76 <= add_ln225_fu_160_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten109_fu_76 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln225_fu_154_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten96_fu_72 <= select_ln226_1_fu_181_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten96_fu_72 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            m27_fu_60 <= m27_15_reload;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            m27_fu_60 <= m27_12_fu_315_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        conv3_i12_i132751_cast_reg_366 <= conv3_i12_i132751_cast_fu_118_p1;
        icmp_ln225_reg_376 <= icmp_ln225_fu_154_p2;
        icmp_ln225_reg_376_pp0_iter1_reg <= icmp_ln225_reg_376;
        icmp_ln226_reg_380 <= icmp_ln226_fu_169_p2;
        sext_ln228_cast_reg_371 <= sext_ln228_cast_fu_122_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        m110_reg_392 <= m110_fu_299_p2;
    end
end

always @ (*) begin
    if (((icmp_ln225_fu_154_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten109_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten109_load = indvar_flatten109_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten96_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten96_load = indvar_flatten96_fu_72;
    end
end

always @ (*) begin
    if (((icmp_ln225_reg_376_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        m27_17_out_ap_vld = 1'b1;
    end else begin
        m27_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m64_ce0_local = 1'b1;
    end else begin
        m64_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln225_fu_160_p2 = (ap_sig_allocacmp_indvar_flatten109_load + 10'd1);

assign add_ln226_1_fu_175_p2 = (ap_sig_allocacmp_indvar_flatten96_load + 8'd1);

assign add_ln226_fu_229_p2 = (select_ln22_fu_205_p3 + 4'd1);

assign add_ln227_fu_283_p2 = (select_ln22_1_fu_240_p3 + 4'd1);

assign add_ln228_fu_272_p2 = (tmp_4_fu_260_p3 + zext_ln228_fu_268_p1);

assign add_ln230_fu_310_p2 = ($signed(conv3_i12_i132751_cast_reg_366) + $signed(sext_ln230_fu_307_p1));

assign and_ln22_fu_223_p2 = (xor_ln22_fu_212_p2 & icmp_ln227_fu_217_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign conv3_i12_i132751_cast_fu_118_p1 = $signed(conv3_i12_i132751);

assign icmp_ln225_fu_154_p2 = ((ap_sig_allocacmp_indvar_flatten109_load == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln226_fu_169_p2 = ((ap_sig_allocacmp_indvar_flatten96_load == 8'd64) ? 1'b1 : 1'b0);

assign icmp_ln227_fu_217_p2 = ((i_n10_2_fu_64 == 4'd8) ? 1'b1 : 1'b0);

assign m110_fu_299_p1 = sext_ln228_cast_reg_371;

assign m27_12_fu_315_p2 = (m27_fu_60 + add_ln230_fu_310_p2);

assign m27_17_out = m27_fu_60;

assign m64_address0 = zext_ln228_1_fu_278_p1;

assign m64_ce0 = m64_ce0_local;

assign or_ln22_fu_235_p2 = (icmp_ln226_reg_380 | and_ln22_fu_223_p2);

assign select_ln226_1_fu_181_p3 = ((icmp_ln226_fu_169_p2[0:0] == 1'b1) ? 8'd1 : add_ln226_1_fu_175_p2);

assign select_ln226_fu_248_p3 = ((and_ln22_fu_223_p2[0:0] == 1'b1) ? add_ln226_fu_229_p2 : select_ln22_fu_205_p3);

assign select_ln22_1_fu_240_p3 = ((or_ln22_fu_235_p2[0:0] == 1'b1) ? 4'd0 : i_n10_2_fu_64);

assign select_ln22_fu_205_p3 = ((icmp_ln226_reg_380[0:0] == 1'b1) ? 4'd0 : i_n10_1_fu_68);

assign sext_ln228_cast_fu_122_p1 = $signed(sext_ln228);

assign sext_ln230_fu_307_p1 = $signed(m110_reg_392);

assign tmp_4_fu_260_p3 = {{trunc_ln228_fu_256_p1}, {3'd0}};

assign trunc_ln228_fu_256_p1 = select_ln226_fu_248_p3[2:0];

assign xor_ln22_fu_212_p2 = (icmp_ln226_reg_380 ^ 1'd1);

assign zext_ln228_1_fu_278_p1 = add_ln228_fu_272_p2;

assign zext_ln228_fu_268_p1 = select_ln22_1_fu_240_p3;

endmodule //case_3_case_3_Pipeline_L_n10_1_L_n10_2_L_n10_3
