// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module case_3_case_3_Pipeline_L_n9_1_L_n9_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m27_13_reload,
        in_data_2_address0,
        in_data_2_ce0,
        in_data_2_q0,
        sext_ln220,
        m27_15_out,
        m27_15_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] m27_13_reload;
output  [3:0] in_data_2_address0;
output   in_data_2_ce0;
input  [7:0] in_data_2_q0;
input  [3:0] sext_ln220;
output  [15:0] m27_15_out;
output   m27_15_out_ap_vld;

reg ap_idle;
reg m27_15_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln218_fu_116_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [9:0] sext_ln220_cast_fu_94_p1;
reg  signed [9:0] sext_ln220_cast_reg_218;
reg   [0:0] icmp_ln218_reg_223;
wire   [9:0] m105_fu_170_p2;
reg   [9:0] m105_reg_232;
wire   [63:0] zext_ln219_fu_145_p1;
wire    ap_block_pp0_stage0;
reg   [15:0] m27_fu_50;
wire   [15:0] m27_4_fu_181_p2;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [3:0] i_n9_1_fu_54;
wire   [3:0] add_ln219_fu_150_p2;
reg   [3:0] ap_sig_allocacmp_i_n9_1_load;
reg   [6:0] indvar_flatten89_fu_58;
wire   [6:0] add_ln218_fu_122_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten89_load;
wire    ap_block_pp0_stage0_01001;
reg    in_data_2_ce0_local;
wire   [0:0] icmp_ln219_fu_131_p2;
wire   [3:0] select_ln22_fu_137_p3;
wire  signed [3:0] m105_fu_170_p1;
wire  signed [15:0] sext_ln222_fu_178_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 m27_fu_50 = 16'd0;
#0 i_n9_1_fu_54 = 4'd0;
#0 indvar_flatten89_fu_58 = 7'd0;
#0 ap_done_reg = 1'b0;
end

case_3_mul_8s_4s_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 10 ))
mul_8s_4s_10_1_1_U84(
    .din0(in_data_2_q0),
    .din1(m105_fu_170_p1),
    .dout(m105_fu_170_p2)
);

case_3_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln218_fu_116_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_n9_1_fu_54 <= add_ln219_fu_150_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_n9_1_fu_54 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln218_fu_116_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten89_fu_58 <= add_ln218_fu_122_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten89_fu_58 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            m27_fu_50 <= m27_13_reload;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            m27_fu_50 <= m27_4_fu_181_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln218_reg_223 <= icmp_ln218_fu_116_p2;
        m105_reg_232 <= m105_fu_170_p2;
        sext_ln220_cast_reg_218 <= sext_ln220_cast_fu_94_p1;
    end
end

always @ (*) begin
    if (((icmp_ln218_fu_116_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_n9_1_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i_n9_1_load = i_n9_1_fu_54;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten89_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten89_load = indvar_flatten89_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_data_2_ce0_local = 1'b1;
    end else begin
        in_data_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln218_reg_223 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m27_15_out_ap_vld = 1'b1;
    end else begin
        m27_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln218_fu_122_p2 = (ap_sig_allocacmp_indvar_flatten89_load + 7'd1);

assign add_ln219_fu_150_p2 = (select_ln22_fu_137_p3 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln218_fu_116_p2 = ((ap_sig_allocacmp_indvar_flatten89_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln219_fu_131_p2 = ((ap_sig_allocacmp_i_n9_1_load == 4'd8) ? 1'b1 : 1'b0);

assign in_data_2_address0 = zext_ln219_fu_145_p1;

assign in_data_2_ce0 = in_data_2_ce0_local;

assign m105_fu_170_p1 = sext_ln220_cast_reg_218;

assign m27_15_out = m27_fu_50;

assign m27_4_fu_181_p2 = ($signed(sext_ln222_fu_178_p1) + $signed(m27_fu_50));

assign select_ln22_fu_137_p3 = ((icmp_ln219_fu_131_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_i_n9_1_load);

assign sext_ln220_cast_fu_94_p1 = $signed(sext_ln220);

assign sext_ln222_fu_178_p1 = $signed(m105_reg_232);

assign zext_ln219_fu_145_p1 = select_ln22_fu_137_p3;

endmodule //case_3_case_3_Pipeline_L_n9_1_L_n9_2
