// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module case_3_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m27_19_reload,
        in_data_0_address0,
        in_data_0_ce0,
        in_data_0_q0,
        sext_ln247,
        in_data_12_address0,
        in_data_12_ce0,
        in_data_12_q0,
        sext_ln22_4,
        sext_ln241,
        conv3_i12_i4097189_phi_reload,
        m120_cast,
        sext_ln108,
        m27_21_out,
        m27_21_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] m27_19_reload;
output  [3:0] in_data_0_address0;
output   in_data_0_ce0;
input  [7:0] in_data_0_q0;
input  [6:0] sext_ln247;
output  [3:0] in_data_12_address0;
output   in_data_12_ce0;
input  [7:0] in_data_12_q0;
input  [7:0] sext_ln22_4;
input  [8:0] sext_ln241;
input  [2:0] conv3_i12_i4097189_phi_reload;
input  [4:0] m120_cast;
input  [3:0] sext_ln108;
output  [15:0] m27_21_out;
output   m27_21_out_ap_vld;

reg ap_idle;
reg m27_21_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln241_fu_218_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [5:0] sext_ln108_cast_fu_171_p1;
reg  signed [5:0] sext_ln108_cast_reg_428;
wire  signed [5:0] m120_cast_cast_fu_175_p1;
reg  signed [5:0] m120_cast_cast_reg_433;
wire  signed [8:0] sext_ln22_4_cast_fu_179_p1;
reg  signed [8:0] sext_ln22_4_cast_reg_438;
wire  signed [8:0] sext_ln247_cast_fu_183_p1;
reg  signed [8:0] sext_ln247_cast_reg_443;
wire  signed [10:0] conv3_i12_i4097189_phi_reload_cast_fu_187_p1;
reg  signed [10:0] conv3_i12_i4097189_phi_reload_cast_reg_448;
wire  signed [9:0] sext_ln241_cast_fu_191_p1;
reg  signed [9:0] sext_ln241_cast_reg_453;
reg   [0:0] icmp_ln241_reg_458;
wire   [9:0] add_ln262_fu_341_p2;
reg   [9:0] add_ln262_reg_472;
wire   [9:0] add_ln262_3_fu_354_p2;
reg   [9:0] add_ln262_3_reg_477;
wire   [63:0] zext_ln243_fu_274_p1;
wire    ap_block_pp0_stage0;
reg   [15:0] m27_fu_80;
wire   [15:0] m27_8_fu_384_p2;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [3:0] i_n12_2_fu_84;
wire   [3:0] add_ln243_fu_280_p2;
reg   [3:0] ap_sig_allocacmp_i_n12_2_load;
reg   [7:0] indvar_flatten123_fu_88;
wire   [7:0] select_ln242_fu_292_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten123_load;
reg   [9:0] indvar_flatten136_fu_92;
wire   [9:0] add_ln241_fu_224_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten136_load;
wire    ap_block_pp0_stage0_01001;
reg    in_data_0_ce0_local;
reg    in_data_12_ce0_local;
wire   [0:0] icmp_ln242_fu_236_p2;
wire   [0:0] icmp_ln243_fu_248_p2;
wire   [0:0] xor_ln22_fu_242_p2;
wire   [0:0] and_ln22_fu_254_p2;
wire   [0:0] or_ln22_fu_260_p2;
wire   [3:0] select_ln22_fu_266_p3;
wire   [7:0] add_ln242_fu_286_p2;
wire  signed [6:0] m122_fu_319_p1;
wire   [8:0] m122_fu_319_p2;
wire  signed [8:0] sext_ln254_fu_328_p1;
wire   [8:0] m126_fu_332_p2;
wire  signed [9:0] sext_ln262_fu_337_p1;
wire   [5:0] add_ln262_2_fu_346_p2;
wire  signed [9:0] sext_ln262_2_fu_350_p1;
wire  signed [9:0] sext_ln83_fu_324_p1;
wire  signed [10:0] sext_ln262_1_fu_363_p1;
wire  signed [10:0] sext_ln262_3_fu_371_p1;
wire   [10:0] add_ln262_1_fu_366_p2;
wire   [10:0] add_ln262_4_fu_374_p2;
wire  signed [15:0] sext_ln262_4_fu_380_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 m27_fu_80 = 16'd0;
#0 i_n12_2_fu_84 = 4'd0;
#0 indvar_flatten123_fu_88 = 8'd0;
#0 indvar_flatten136_fu_92 = 10'd0;
#0 ap_done_reg = 1'b0;
end

case_3_mul_8s_7s_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 9 ))
mul_8s_7s_9_1_1_U104(
    .din0(in_data_0_q0),
    .din1(m122_fu_319_p1),
    .dout(m122_fu_319_p2)
);

case_3_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln241_fu_218_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_n12_2_fu_84 <= add_ln243_fu_280_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_n12_2_fu_84 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln241_fu_218_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten123_fu_88 <= select_ln242_fu_292_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten123_fu_88 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln241_fu_218_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten136_fu_92 <= add_ln241_fu_224_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten136_fu_92 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            m27_fu_80 <= m27_19_reload;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            m27_fu_80 <= m27_8_fu_384_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln262_3_reg_477 <= add_ln262_3_fu_354_p2;
        add_ln262_reg_472 <= add_ln262_fu_341_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        conv3_i12_i4097189_phi_reload_cast_reg_448 <= conv3_i12_i4097189_phi_reload_cast_fu_187_p1;
        icmp_ln241_reg_458 <= icmp_ln241_fu_218_p2;
        m120_cast_cast_reg_433 <= m120_cast_cast_fu_175_p1;
        sext_ln108_cast_reg_428 <= sext_ln108_cast_fu_171_p1;
        sext_ln22_4_cast_reg_438 <= sext_ln22_4_cast_fu_179_p1;
        sext_ln241_cast_reg_453 <= sext_ln241_cast_fu_191_p1;
        sext_ln247_cast_reg_443 <= sext_ln247_cast_fu_183_p1;
    end
end

always @ (*) begin
    if (((icmp_ln241_fu_218_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_n12_2_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i_n12_2_load = i_n12_2_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten123_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten123_load = indvar_flatten123_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten136_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten136_load = indvar_flatten136_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_data_0_ce0_local = 1'b1;
    end else begin
        in_data_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_data_12_ce0_local = 1'b1;
    end else begin
        in_data_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln241_reg_458 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        m27_21_out_ap_vld = 1'b1;
    end else begin
        m27_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln241_fu_224_p2 = (ap_sig_allocacmp_indvar_flatten136_load + 10'd1);

assign add_ln242_fu_286_p2 = (ap_sig_allocacmp_indvar_flatten123_load + 8'd1);

assign add_ln243_fu_280_p2 = (select_ln22_fu_266_p3 + 4'd1);

assign add_ln262_1_fu_366_p2 = ($signed(sext_ln262_1_fu_363_p1) + $signed(conv3_i12_i4097189_phi_reload_cast_reg_448));

assign add_ln262_2_fu_346_p2 = ($signed(m120_cast_cast_reg_433) + $signed(sext_ln108_cast_reg_428));

assign add_ln262_3_fu_354_p2 = ($signed(sext_ln262_2_fu_350_p1) + $signed(sext_ln83_fu_324_p1));

assign add_ln262_4_fu_374_p2 = ($signed(sext_ln262_3_fu_371_p1) + $signed(add_ln262_1_fu_366_p2));

assign add_ln262_fu_341_p2 = ($signed(sext_ln241_cast_reg_453) + $signed(sext_ln262_fu_337_p1));

assign and_ln22_fu_254_p2 = (xor_ln22_fu_242_p2 & icmp_ln243_fu_248_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign conv3_i12_i4097189_phi_reload_cast_fu_187_p1 = $signed(conv3_i12_i4097189_phi_reload);

assign icmp_ln241_fu_218_p2 = ((ap_sig_allocacmp_indvar_flatten136_load == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln242_fu_236_p2 = ((ap_sig_allocacmp_indvar_flatten123_load == 8'd64) ? 1'b1 : 1'b0);

assign icmp_ln243_fu_248_p2 = ((ap_sig_allocacmp_i_n12_2_load == 4'd8) ? 1'b1 : 1'b0);

assign in_data_0_address0 = zext_ln243_fu_274_p1;

assign in_data_0_ce0 = in_data_0_ce0_local;

assign in_data_12_address0 = zext_ln243_fu_274_p1;

assign in_data_12_ce0 = in_data_12_ce0_local;

assign m120_cast_cast_fu_175_p1 = $signed(m120_cast);

assign m122_fu_319_p1 = sext_ln247_cast_reg_443;

assign m126_fu_332_p2 = ($signed(sext_ln254_fu_328_p1) + $signed(sext_ln22_4_cast_reg_438));

assign m27_21_out = m27_fu_80;

assign m27_8_fu_384_p2 = ($signed(m27_fu_80) + $signed(sext_ln262_4_fu_380_p1));

assign or_ln22_fu_260_p2 = (icmp_ln242_fu_236_p2 | and_ln22_fu_254_p2);

assign select_ln22_fu_266_p3 = ((or_ln22_fu_260_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_i_n12_2_load);

assign select_ln242_fu_292_p3 = ((icmp_ln242_fu_236_p2[0:0] == 1'b1) ? 8'd1 : add_ln242_fu_286_p2);

assign sext_ln108_cast_fu_171_p1 = $signed(sext_ln108);

assign sext_ln22_4_cast_fu_179_p1 = $signed(sext_ln22_4);

assign sext_ln241_cast_fu_191_p1 = $signed(sext_ln241);

assign sext_ln247_cast_fu_183_p1 = $signed(sext_ln247);

assign sext_ln254_fu_328_p1 = $signed(in_data_12_q0);

assign sext_ln262_1_fu_363_p1 = $signed(add_ln262_reg_472);

assign sext_ln262_2_fu_350_p1 = $signed(add_ln262_2_fu_346_p2);

assign sext_ln262_3_fu_371_p1 = $signed(add_ln262_3_reg_477);

assign sext_ln262_4_fu_380_p1 = $signed(add_ln262_4_fu_374_p2);

assign sext_ln262_fu_337_p1 = $signed(m126_fu_332_p2);

assign sext_ln83_fu_324_p1 = $signed(m122_fu_319_p2);

assign xor_ln22_fu_242_p2 = (icmp_ln242_fu_236_p2 ^ 1'd1);

assign zext_ln243_fu_274_p1 = select_ln22_fu_266_p3;

endmodule //case_3_case_3_Pipeline_L_n12_1_L_n12_2_L_n12_3
